Modify initialization routines to use new OpenFOAM data
LLNL/ExaCA pull request #10
Opened 2021-09-10 14:06 UTC by MattRolchigo

OpenFOAM no longer prints domain extent in temperature files - ParallelMeshInit has been modified to read temperature data twice: first to determine domain size and perform the decomposition, then to store the appropriate portions of the temperature data on the appropriate MPI ranks.

To account for the increased precision in OpenFOAM output, ExaCA reads the temperature data into a structure of type "double", rather than the "float" structure previously used

2021-09-10 16:30 UTC, streeve reviewed
This would be a good case to create a unit test for - correctly read in a very small FOAM data file

2021-09-10 16:30 UTC, streeve commented on src/runCA.cpp
> +    std::vector<double> RawData(1000000);
As usual, I'm suggesting we convert this to a View

2021-09-10 16:30 UTC, streeve commented on src/CAinitialize.cpp
> +                    XCoordinates.resize(XYZPointCounter + 1000000);
Why do you keep the extra buffer after counting?

2021-09-10 16:30 UTC, streeve commented on src/CAinitialize.cpp
> +    // removed unused LayerwiseTSOffset variable
Is this important to know here?

2021-09-11 05:32 UTC, MattRolchigo commented on src/runCA.cpp
> +    std::vector<double> RawData(1000000);
I feel like at one point there was a reason this structure was a vector instead of a view... but I don't see a reason it can't be a view now

2021-09-11 05:38 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +                    XCoordinates.resize(XYZPointCounter + 1000000);
These buffers (XCoordinates, YCoordinates, ZCoordinates) have an initial guess for size (1000000), and are resized once they fills up (by adding 1000000 to the size). When the reading of points is complete, it is resized to the actual number of data points

2021-09-11 05:43 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +    // removed unused LayerwiseTSOffset variable
Kind of... this variable was just sitting there doing nothing, the new variable SmallestTime_Global takes on the role of what LayerwiseTSOffset was (at some point intended to do), aka make sure that each layer's "critical time step" starts at 0/time step 0 corresponds to the smallest value of "liquidus time" from the temperature data for the layer

2021-09-11 06:44 UTC, MattRolchigo commented on src/runCA.cpp
> +    std::vector<double> RawData(1000000);
I take that back, I played around with this and something about declaring RawData in RunProgram_Reduced, resizing RawData inside of ParallelMeshInit, and then passing it to TempInit_Reduced seems to mess things up and give an error when accessing RawData in TempInit_Reduced. I'm going to leave this as a vector for now, since the point of addressing this vector at all was to change the data type to account for added precisions from OpenFOAM, and converting this to a view may require more thought/debugging time than I expected

2021-09-13 15:17 UTC, streeve requested changes
With a couple new functions to clean things up (and maybe there are others you can think of) this should be ready

2021-09-13 15:17 UTC, streeve commented on src/CAinitialize.cpp
> +                throw std::runtime_error(error);
Should create a small function for this and call for each variable - then the error can be more specific

2021-09-13 15:17 UTC, streeve commented on src/CAinitialize.cpp
> +                std::size_t FirstComma = s.find(",");
Now that you do this twice, this should be a separate function passing the input line and line values

2021-09-13 18:26 UTC, streeve commented on src/CAinitialize.cpp
> +void checkForValues(std::string HeaderLine, std::string Check1, std::string Check2, std::string Check3) {
I like this, but this doesn't enforce the order assumed in the next function

2021-09-13 18:33 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +void checkForValues(std::string HeaderLine, std::string Check1, std::string Check2, std::string Check3) {
Yeah, I realized that - what I had before didn't enforce that order either actually. I kind of want to change this section so that the header must have x, y, z, tm, tl, cr in that order, and any wrong capitalization or order would throw an error like:
"Header line must list, in order, x, y, z, tm ,tl , cr: the header line of the temperature data file instead lists [insert first line from file]"

2021-09-13 19:00 UTC, streeve commented on src/CAinitialize.cpp
> +void checkForValues(std::string HeaderLine, std::string Check1, std::string Check2, std::string Check3) {
You could allow "x y z tm tl cr" or "X Y Z Tm Tl Cr" and maybe all caps and nothing else

2021-09-13 19:07 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +void checkForValues(std::string HeaderLine, std::string Check1, std::string Check2, std::string Check3) {
I think I'll change the function to take in the full header line, compare each of the 6 substrings by position against the expected values and maybe 2 alternative values, and then throw a position-specific runtime error if there's no match

2021-09-14 19:57 UTC, streeve requested changes
Couple more changes

2021-09-15 21:03 UTC, streeve approved these changes

2021-09-15 21:06 UTC, merged