Updated example problems and README to include problems with remelting
LLNL/ExaCA pull request #111
Opened 2022-09-20 20:11 UTC by MattRolchigo

2022-09-21 15:25 UTC, streeve requested changes

2022-09-21 15:25 UTC, streeve commented on .github/workflows/CI.yml
> +          $HOME/exaca/bin/ExaCA-Kokkos Inp_SmallSpotMelt_RM.txt
Maybe we only run examples with 2 ranks? We're up to about 5 min with debug on this PR and the unit test suite is starting to cover quite a bit

2022-09-21 15:25 UTC, streeve commented on examples/Inp_SmallSpotMelt_RM.txt
> +Problem type: SM
Worth considering if we should rename old files as "NoRemelt"

2022-09-21 15:25 UTC, streeve commented on examples/README.md
> +ExaCA currently can model five types of problems:
I would still say 3, with and without remelting

2022-09-21 15:38 UTC, MattRolchigo commented on .github/workflows/CI.yml
> +          $HOME/exaca/bin/ExaCA-Kokkos Inp_SmallSpotMelt_RM.txt
Fair enough, we could also turn debug printing/intermediate file output (which is a significant portion of the run time for these tiny examples) off for the 1 rank runs of SmallDirSolidification and SmallSpotMelt. I agree though, for the remelting spot test problem, no intermediate output + 2 ranks should be the only thing we do

2022-09-27 18:13 UTC, MattRolchigo commented on examples/Inp_SmallSpotMelt_RM.txt
> +Problem type: SM
I'm reluctant to change the names of existing example problems - plus, since only 2 of the problems use remelting, I think it's reasonable to consider "no remelting" as the default for tests and only having "_RM" at the end of the examples that do consider remelting to avoid having unnecessarily long file names

2022-09-27 19:35 UTC, streeve approved these changes

2022-09-27 19:35 UTC, streeve commented on .github/workflows/CI.yml
>            $HOME/exaca/bin/ExaCA-Kokkos Inp_SmallDirSolidification.txt
Should consider removing the other 1 rank runs (separately if you prefer)

2022-09-27 19:35 UTC, streeve commented on examples/README.md
> +* Problem types SM and RM modify problem types S and R to include multiple melting and solidification events per cell. For problem types S and R all cells that will eventually undergo melting are ini
))

2022-09-29 18:13 UTC, merged