Create interfacial repsponse function class
LLNL/ExaCA pull request #123
Opened 2022-10-18 14:49 UTC by streeve

Needs to be tested on the device

2022-10-18 16:43 UTC, MattRolchigo commented on src/runCA.cpp
> +    irf.normalize(deltat, deltax);
This could actually be called inside of InputReadFromFile after these parameters have been initialized, since they aren't used or changed at any other point during initialization. Also I'm now realizing that DConst should also be normalized as well... since it is 0 for the material we've been using, it didn't matter, but that's a bug in ExaCA

2022-10-18 16:58 UTC, streeve commented on src/runCA.cpp
> +    irf.normalize(deltat, deltax);
Good point - maybe better to do that in a separate PR first to make it obvious?

2022-10-18 21:36 UTC, MattRolchigo commented on src/CAinitialize.hpp
> +std::string InputReadFromFile(int id, std::string InputFile, std::string &SimulationType, int &DecompositionStrategy,
Well now that I think about it, the material file is only defined locally inside of `InputReadFromFile`, while all of the other file names are initialized in `InputReadFromFile` but are passed into the subroutine by reference and used elsewhere. So for consistency, it's probably better than MaterialFile is another string passed by reference into `InputReadFromFile`, with the construction of the IRF class and associated initialization of FreezingRange, A, B, C, and D done inside of runCA.cpp where you have it now

2022-10-18 21:57 UTC, streeve commented on src/runCA.cpp
> +    irf.normalize(deltat, deltax);
Done in #125

2022-10-18 21:57 UTC, streeve commented on src/CAinitialize.hpp
> +std::string InputReadFromFile(int id, std::string InputFile, std::string &SimulationType, int &DecompositionStrategy,
Agreed - done

2022-10-18 21:58 UTC, streeve commented on src/runCA.cpp
> +    irf.normalize(deltat, deltax);
Also improved in 2fc276b736fba61f9ec6f5b3f87f9ed58db6a164

2022-10-19 19:08 UTC, MattRolchigo approved these changes

2022-10-19 19:08 UTC, MattRolchigo commented
I'm ready to merge once that conflict is fixed

2022-10-19 19:09 UTC, MattRolchigo requested changes
I'm ready to merge once that conflict is fixed

2022-10-19 22:40 UTC, streeve commented
So no requested changes?

2022-10-20 16:50 UTC, MattRolchigo commented
Nope, I'm good

2022-10-20 16:51 UTC, MattRolchigo approved these changes

2022-10-20 17:18 UTC, merged