Halostructs
LLNL/ExaCA pull request #126
Opened 2022-10-19 19:02 UTC by MattRolchigo

I get an "undefined symbols" error during compilation, though I'm not sure why - maybe something in the cmake file?

2022-10-19 19:05 UTC, MattRolchigo commented
The change set looks bigger than it is because it was based from #122 instead of master, most of the changes here are from that PR

2022-10-19 22:25 UTC, streeve commented
> I get an "undefined symbols" error during compilation

You were just missing the destructor

2022-10-19 22:40 UTC, streeve requested changes
I still think separating the new comm buffer type and the new halo class is worth the time, but this is close to ready probably

2022-10-19 22:40 UTC, streeve commented on src/Halo.cpp
> +#include "Halo.hpp"
I think these files should just be name CAhalo.hpp and also include the free functions in ghostnodes

2022-10-19 22:40 UTC, streeve commented on src/Halo.cpp
> +    BufferSouthSend = ViewBuffer("BufferNS", 5 * BufSizeX * BufSizeZ);
Extra 5?

2022-10-19 22:40 UTC, streeve commented on src/Halo.cpp
> +    BufferSouthRecv = BufferSouthSend;
This is not going to go well.. they should all be created separately

2022-10-19 22:40 UTC, streeve commented on src/CAtypes.hpp
> +struct Buffer {
Maybe `CommData` or something?

2022-10-19 22:40 UTC, streeve commented on src/Halo.hpp
> +  public:
May as well make it a struct if everything is going to be public

2022-10-19 22:40 UTC, streeve commented on src/CAghostnodes.hpp
> +KOKKOS_INLINE_FUNCTION void loadghostnodes(const int GhostGID, const float GhostDOCX, const float GhostDOCY,
I would consider making all of these member functions of `Halo`

2022-10-31 13:51 UTC, MattRolchigo commented
Current status: 

- Compiles on Serial and Pthreads backends
- Compiles with warnings with Cuda backend ("calling a __host__ function("Halo::~Halo") from a __host__ __device__ function("") is not allowed", and ("Implicit capture of 'this' in extended lambda expression")
- Compiles with warnings with HIP backend ("capture host side class data member by this pointer in device or host device lambda function may result in invalid memory access if this pointer is not accessible on device side [-Wgpu-maybe-wrong-side]") - BufferSouthSend in CAhalo.cpp

2023-03-30 17:50 UTC, closed without merging