New analysis executable for AMBench microstructure
LLNL/ExaCA pull request #136
Opened 2022-10-27 15:58 UTC by MattRolchigo

2022-10-27 16:18 UTC, streeve requested changes
Not sure if the print functions need to be separate files - there's already an ExaConstit-specific function in the "main" analysis

2022-10-27 16:18 UTC, streeve commented on analysis/src/CMakeLists.txt
> +add_executable(amb_grain_analysis ${EXAGA_AMB_SOURCES})
I would go with `grain_analysis_amb`

2022-10-27 16:18 UTC, streeve commented on analysis/src/GAutils.hpp
> +static std::vector<double> DEFAULT_VECTOR;
What

2022-10-27 16:18 UTC, streeve commented on analysis/src/runGA_AMB.cpp
> +int main(int argc, char *argv[]) {
Is there a quick run you can add to the CI?

2022-10-27 17:30 UTC, streeve commented on analysis/src/GAutils.hpp
> +static std::vector<double> DEFAULT_VECTOR;
Seems much simpler to return the vector and ignore if not needed

2022-10-27 17:31 UTC, streeve commented on analysis/src/GAutils.cpp
> +    // If log file contained the X, Y, Z bounds of the domain and they're used in the analysis, convert them
Won't the parsing above fail if the bounds aren't included?

2022-10-27 18:41 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +    // If log file contained the X, Y, Z bounds of the domain and they're used in the analysis, convert them
Yes - only ExaCA simulation results starting with this commit are compatible with this new analysis executable. I don't really see a reason why I'd need to run this new analysis script using any of the older datasets, though I should probably throw a specific error if I accidentally do try to run this with an old dataset

2022-10-27 18:48 UTC, MattRolchigo commented
Regarding the print functions, since the old analysis script exclusively uses print functions from GAprint, and the new analysis script exclusively uses print functions from GAprint_AMB, it seemed like having separate files was a more logical way to divide things. There is probably a better way to deal with the redundancy between PrintExaConstitRVEData in GAprint and PrintExaConstitDefaultRVE in CAprint, but the new analysis script does not print ExaConstit data (for the ExaAM challenge problem, we're relying on PrintExaConstitDefaultRVE being called as part of running ExaCA)

2022-10-27 19:13 UTC, MattRolchigo commented
the addition of AnalyzeThickLeg.txt in analysis/examples was a mistake, that file has been removed. The new analysis executable does not require an input file, just a command line path/name of the dataset

2022-10-27 22:38 UTC, streeve commented on analysis/src/GAprint_AMB.cpp
> +#include <algorithm>
Do you really need all these headers? They're also duplicated from the header

2022-10-27 22:38 UTC, streeve commented on analysis/src/GAutils.cpp
> +void ParseFilenames_AMB(std::string BaseFileName, std::string &LogFile, std::string &MicrostructureFile,
Can't this call `ParseFilenames` and live in the AMB header?

2022-10-27 22:38 UTC, streeve commented on analysis/src/GAprint_AMB.cpp
> +void WriteEulerAngleData_AMB(std::ofstream &Grainplot, ViewI3D_H &GrainID, int i, int j, int k,
I feel like all of these functions should call a corresponding method from `GAprint` somewhere

2022-10-28 13:06 UTC, MattRolchigo commented on analysis/src/GAprint_AMB.cpp
> +#include <algorithm>
Probably not. They're in GAprint.cpp too and don't need to be, I'll remove them

2022-10-28 13:08 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +void ParseFilenames_AMB(std::string BaseFileName, std::string &LogFile, std::string &MicrostructureFile,
Despite the similar names, ParseFilenames and ParseFilenames_AMB are actually pretty different. ParseFilenames actually reads and parses an input file, while ParseFilenames_AMB just takes the command line input and checks that the files exist/are installed. Maybe renaming ParseFilenames_AMB to CheckInputFiles would be more appropriate to reflect this difference

2022-10-28 13:18 UTC, MattRolchigo commented on analysis/src/GAprint_AMB.cpp
> +void WriteEulerAngleData_AMB(std::ofstream &Grainplot, ViewI3D_H &GrainID, int i, int j, int k,
I'm not 100% sure what you mean, there's some repeated code that could be removed by rewriting/combining parts of WriteEulerAngleData_AMB and PrintCrossSectionOrientationData. But PrintXYCrossSectionSeries_AMB and PrintDefaultCrossSectionData_AMB are pretty distinct from anything done inside of GAprint, I don't see how that would work

2022-10-28 14:58 UTC, streeve commented on analysis/src/GAutils.cpp
> +void ParseFilenames_AMB(std::string BaseFileName, std::string &LogFile, std::string &MicrostructureFile,
Rename sounds good to me

2022-10-28 14:58 UTC, streeve commented on analysis/src/GAprint_AMB.cpp
> +void WriteEulerAngleData_AMB(std::ofstream &Grainplot, ViewI3D_H &GrainID, int i, int j, int k,
I would refactor Euler then and rename the others to distinguish if they're that different

2022-11-01 19:47 UTC, streeve requested changes

2022-11-01 20:10 UTC, MattRolchigo commented on analysis/src/GAprint.cpp
> +        static_cast<double>(AreaGrainsAboveThreshold) / static_cast<double>(CrossSectionSize);
Like a function that takes two ints as input parameters, casts them to doubles, and returns the quotient as a double? That seemed pretty specific to me at first, but I realized I actually do this operation multiple times in the code...

2022-11-01 21:41 UTC, streeve commented on analysis/src/GAutils.cpp
> +void CheckInputFiles_AMB(std::string BaseFileName, std::string &LogFile, std::string &MicrostructureFile,
The clutter seems worth not having this in GAutils to me

2022-11-01 22:44 UTC, streeve reviewed
Unless it's worth doing the size calculation on device, then printing separately, I think this is basically ready

2022-11-01 22:44 UTC, streeve commented on analysis/src/runGA_AMB.cpp
> +    {
You don't need this extra scope if you're using init/finalize

2022-11-01 22:44 UTC, streeve commented on analysis/src/GAprint.cpp
> +    for (int n = 0; n < NumberOfGrains; n++) {
Is this ever enough of a bottleneck to do it on the device?

2022-11-01 22:44 UTC, streeve commented on analysis/src/GAutils.cpp
> +    return quotient;
```suggestion
template <typename ReturnType, typename FirstType, typename SecondType>
ReturnType DivideInts(FirstType Int1, SecondType Int2) {
    return static_cast<ReturnType>(Int1) / static_cast<ReturnType>(Int2);
```

2022-11-01 22:44 UTC, streeve commented on analysis/src/GAutils.cpp
> +    return quotient;
Then you can use this for floats/different input types too

2022-11-02 13:06 UTC, MattRolchigo commented on analysis/src/GAprint.cpp
> +    for (int n = 0; n < NumberOfGrains; n++) {
Since we just call it on individual cross-sections, there are never enough grains that it becomes a bottleneck. Some of the older analysis routines that we call on a volume of material could benefit from being done on the device, though

2022-11-02 13:07 UTC, MattRolchigo commented on analysis/src/runGA_AMB.cpp
> +    {
We do the same thing in runGA.cpp, I didn't want to change things up here

2022-11-02 13:20 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +    return quotient;
I tried something this and couldn't get it to work, with compilation errors about `candidate template ignored: couldn't infer template argument 'ReturnType'`. I'm assuming I'd need a copy of the line `template <typename ReturnType, typename FirstType, typename SecondType>` in the .hpp file too, but even with that I get the error

2022-11-02 19:29 UTC, streeve reviewed
I'll approve after current comments are resolved

2022-11-02 19:29 UTC, streeve commented on analysis/src/GAutils.hpp
> +ReturnType DivideCast(FirstType Int1, SecondType Int2) {
On second glance, we should probably name them `Input1` and `Input2`

2022-11-02 19:29 UTC, streeve commented on analysis/src/runGA_AMB.cpp
> +    {
I'd rather fix it here and fix others later

2022-11-02 21:02 UTC, streeve approved these changes

2022-11-02 21:22 UTC, merged