Option to only read/store temperature data for one layer at a time
LLNL/ExaCA pull request #137
Opened 2022-11-02 20:14 UTC by MattRolchigo

By default, ExaCA reads and stores any temperature data associated with a given problem during code initialization. This update adds the option to only store one layer's temperature data at a time, reading each additional temperature file at the start of that layer and discarding the previous layer's temperature data. This will avoid program memory issues for simulations that use several sets of time-temperature history data for multilayer simulations (as opposed to the current example problems, which use one set of data for each layer, or alternate between two data sets for even and odd layers).

2022-11-03 18:23 UTC, streeve reviewed
Mostly just questions, but I really doubt clearing the vector is helping us here

2022-11-03 18:30 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +        double ZMin_ThisLayer = 1000000;
Since these are in meters, either the simulation domain would have to use a really funky coordinate system where the origin is at Z = 1000000 or larger, or someone is creating a part with roughly the area of Texas. There's probably a better way to do this, but that's been in the code for around 2 years

2022-11-03 18:32 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +        // Determine Z bounds of this layer, in case they are different than those of the first layer
Yeah that block should've been deleted, I must have missed it when cleaning up the code

2022-11-08 14:58 UTC, streeve commented on src/CAinitialize.cpp
> +        double ZMin_ThisLayer = 1000000;
`std::numeric_limits<double>::max()` would be more safe

2022-11-08 15:13 UTC, streeve requested changes

2022-11-08 19:18 UTC, MattRolchigo commented on unit_test/tstInit.cpp
> +        // Read in data to "RawData" (initial guess at size shouldn't matter)
The initial guess at the size shouldn't make a difference in the test results, since the ReadTemperature function should be resizing it as necessary

2022-11-08 19:36 UTC, MattRolchigo commented on src/runCA.cpp
>          RawData.clear();
If we have remelting, it probably makes sense to just resize it as necessary inside of `ReadTemperatureData` instead of resizing it to a guess or clearing it. As of right now, if we don't have remelting, we don't need this vector following the initial call to TempInit... but in the future, I'm planning on the "no remelt" simulations to be initialized layer by layer, which means that we will need to hold on to it. So we might as well just never clear it

2022-11-08 22:48 UTC, streeve commented on src/CAinitialize.cpp
>                  RawData[NumberOfTemperatureDataPoints] = getInputDouble(ParsedLine[2]);
This should be guarded by a resize if the increment exceeds the size. I think it's just always been large enough of an initial guess

2022-11-08 22:48 UTC, streeve commented on unit_test/tstInit.cpp
> +        // Read in data to "RawData" (initial guess at size shouldn't matter)
But it doesn't resize before placing data does it? Maybe I'm missing something

2022-11-09 16:52 UTC, MattRolchigo commented on unit_test/tstInit.cpp
> +        // Read in data to "RawData" (initial guess at size shouldn't matter)
Yeah I just changed the comment back to what it was, there was no need to try and explain anything special here

2022-11-09 16:53 UTC, MattRolchigo commented on src/CAinitialize.cpp
>                  RawData[NumberOfTemperatureDataPoints] = getInputDouble(ParsedLine[2]);
It is guarded, it adds the values into RawData 6 at a time, and then checks to see if the number of values is within 6 of the size on line 820

2022-11-09 17:17 UTC, streeve approved these changes

2022-11-09 17:17 UTC, streeve commented on src/CAinitialize.cpp
>                  RawData[NumberOfTemperatureDataPoints] = getInputDouble(ParsedLine[2]);
My bad - not sure how I missed that after searching for `resize`. I think we need a follow-up that makes the resize increment configurable, but not really in scope here. And with that I would lean towards a fractional increment

2022-11-09 18:25 UTC, merged