Writing and reading of ExaCA output data as binary
LLNL/ExaCA pull request #138
Opened 2022-11-03 17:59 UTC by MattRolchigo

Added the option to print ExaCA vtk data as binary data (instead of ASCII, which is currently used by default) to reduce the output file sizes. To support this, new functions were added to read and write binary data, and convert between little and big endian format, and a new unit test was written to test the binary input/output.

2022-11-08 15:28 UTC, streeve requested changes
Can you update the description? I know you added changes specifically for reduced precision in some places in addition to the binary option

2022-11-08 15:28 UTC, streeve commented on src/CAparsefiles.hpp
> +template <typename SwapType>
I think this needs a comment desciption

2022-11-08 15:28 UTC, streeve commented on src/CAprint.cpp
> +            if (!(PrintBinary))
Is it bad to end on a newline for binary?

2022-11-08 15:28 UTC, streeve commented on src/CAprint.cpp
> +    if (PrintBinary)
I would prefer to pass the `bool` & string, then move this `if` into the `writeData` function

2022-11-08 15:28 UTC, streeve commented on src/CAprint.hpp
> +void WriteBinaryData(std::ofstream &outstream, PrintType PrintValue, bool SwapEndianYN) {
Seems like the endian bool should have a default

2022-11-08 18:03 UTC, MattRolchigo commented on src/CAprint.cpp
> +            if (!(PrintBinary))
The newline was only necessary for the ASCII format (I believe, it might not have been necessary to begin with), it shouldn't be needed for the binary or ASCII really

2022-11-08 22:55 UTC, streeve commented on src/CAparsefiles.hpp
> +template <typename SwapType>
I think this needs line by line comment descriptions

2022-11-08 22:55 UTC, streeve commented on src/CAprint.cpp
> +                if (PrintBinary)
Let's also move this `if` block into a general `writeData` function that does either binary or plain text

2022-11-08 22:55 UTC, streeve commented on src/CAprint.cpp
> +            if (!(PrintBinary))
Why not print for either or both then?

2022-11-09 16:06 UTC, MattRolchigo commented on src/CAprint.cpp
> +            if (!(PrintBinary))
Turns out, the newline isn't actually needed for the ASCII format (that's something in the code that hasn't been touched in 2 years, and was probably in there "just in case")

2022-11-09 17:20 UTC, streeve commented on src/CAprint.cpp
> +            if (!(PrintBinary))
Looks like the newline is necessary in some cases based on the CI failure

2022-11-09 17:22 UTC, streeve commented on unit_test/tstInit.cpp
> +        WriteData(TestIntData, IntData[n], true, true);
Let's call this function with both binary and text (this test should catch the current CI error in addition to the analysis script)

2022-11-09 17:24 UTC, streeve commented on src/CAprint.cpp
> +void OpenPrintHeader(std::ofstream &ParaviewOutputStream, std::string FName, bool PrintBinary, int nx, int ny, int nz,
`writeHeader`?

2022-11-09 18:08 UTC, MattRolchigo commented on unit_test/tstInit.cpp
> +        WriteData(TestIntData, IntData[n], true, true);
Yeah this error is from the fact that I didn't account for the removal of the newlines in the ASCII file read in `ReadASCIIField`, I'll have to fix that and add a test

2022-11-09 18:10 UTC, MattRolchigo commented on unit_test/tstInit.cpp
> +        WriteData(TestIntData, IntData[n], true, true);
`ReadASCIIField` should also account for the fact that vtk files printed prior to this commit will have the newlines, while the ones from this point on will not

2022-11-09 19:59 UTC, MattRolchigo commented on src/CAprint.cpp
> +            if (!(PrintBinary))
Yeah I forgot about the fact that there's multiple fields of vtk data in some files that need to be separated from others with header lines on new lines

2022-11-09 22:51 UTC, MattRolchigo commented on src/CAprint.cpp
> +            if (!(PrintBinary))
So it turns out, printing the newline at the end of the field data messes up the binary read. `outstream.write((char *)&somebinaryvalue, somebinarysize)` followed by `outstream << "Next field header data << std::endl;` works, but having any other lines in there does not. But the `std::endl;` is still needed at the end of ASCII field data, since otherwise it don't print the next field's header data to a new line

2022-11-11 16:19 UTC, streeve approved these changes

2022-11-11 17:44 UTC, merged