Updated baseplate generation algorithm
LLNL/ExaCA pull request #146
Opened 2022-12-01 18:45 UTC by MattRolchigo

Improved performance for generation of the equiaxed baseplate microstructure for small substrate grain size (no effect for larger grain sizes, but up to an order of magnitude speedup for `BaseplateInit_FromGrainSpacing` for large domains and substrate grain sizes equal to the cell size). Also avoids assigning two baseplate grain centers to the same cell, which would previously lead to the generated substrates having a slightly larger mean grain size than the input value (negligible effect for input grain sizes 5x or more larger than the cell size, where two baseplate grains being assigned the same cell was more rare).

2022-12-06 23:29 UTC, streeve requested changes

2022-12-06 23:29 UTC, streeve commented on src/CAinitialize.cpp
> +    Kokkos::parallel_for(
Add comment that this assumes zero-init

2022-12-06 23:29 UTC, streeve commented on src/CAinitialize.cpp
> +    double BaseplateVolume = BaseplateSize * pow(deltax, 3) * pow(10, 18); // in cubic microns
I'm confused on volume vs area here

2022-12-22 20:52 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +    Kokkos::parallel_for(
This was done (lines 1888-1889)

2022-12-22 21:00 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +    ViewI_H BaseplateGrainLocations_Host(Kokkos::ViewAllocateWithoutInitializing("BaseplateGrainLocations_Host"),
I changed the way I did this to make it a little easier to follow. It isn't a straight copy of BaseplateGrainLocations to BaseplateGrainLocations_Host and BaseplateGrainIDs to BaseplateGrainIDs_Host, we're only copying values if BaseplateGrainIDs(i) is non-zero. The size of the structures is different as well; the vectors contain an entry for each cell in the baseplate, while the host views only contain enough entries for the number of baseplate grains (i.e., the size of the vectors minus the number of indices where BaseplateGrainIDs(i) was 0)

2023-01-03 23:13 UTC, streeve commented on src/CAinitialize.cpp
> +    ViewI_H BaseplateGrainLocations_Host(Kokkos::ViewAllocateWithoutInitializing("BaseplateGrainLocations_Host"),
I agree this is easier to follow than before, but can't you generate the random list of grain centers sampling from the total cell volume? The shuffle works, but seems unnecessary. If it's more important to merge the rest of these changes, we could create an issue for what I'm suggesting (and if this suggestion would work it's then likely less work to just do it on the device anyway)

2023-01-04 21:24 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +    ViewI_H BaseplateGrainLocations_Host(Kokkos::ViewAllocateWithoutInitializing("BaseplateGrainLocations_Host"),
The shuffle vs random sampling is done to make sure that a cell isn't assigned more than 1 grain center. For the substrate grain sizes relevant to AM problems, this approach gives approximately the same performance or better performance than the current subroutine. For very large substrate grain sizes (or single crystal/bicrystal substrates) a different approach may be preferable, but that would likely be a separate PR/init subroutine

2023-01-04 21:42 UTC, streeve approved these changes

2023-01-05 04:13 UTC, merged