Option to use json format for all input files
LLNL/ExaCA pull request #156
Opened 2022-12-14 19:08 UTC by MattRolchigo

2022-12-16 14:52 UTC, streeve requested changes
Looks like it's failing because a json file calls the old input

2022-12-19 23:14 UTC, MattRolchigo commented on .github/workflows/CI.yml
> -            json: 'OFF'
In that case, should the CI only be running with the .txt version of the input problems?

2022-12-19 23:15 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +void InputReadFromFile_json(int id, std::string InputFile, std::string &SimulationType, double &deltax, double &NMax,
So do you think that the "new" versions of functions should just be given the old name, and the "old" versions named things like `InputReadFromFile_old`?

2022-12-19 23:18 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +       "PrintFieldsInit": {
I actually tried that first, but in that case you have to check each position in the list against each possible input, and I hadn't realized that using .count() was a thing so it was harder than it should've been

2022-12-19 23:22 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +   "TemperatureData": {
Yes because for the problems that don't use a temperature data file (C and S), the thermal gradient and cooling rate would be given here. Unless we made separate temperature input files for those problem types analogous to the files like `examples/Temperatures/T_AMBenchMultilayer.json`

2022-12-19 23:23 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +   "TemperatureData": {
And if we were going to do that, I'd rather just get rid of the temperature input files altogether and just have that information in the main input file

2022-12-20 19:43 UTC, streeve reviewed
CI errors now seem to be about the input file itself

2022-12-20 19:43 UTC, streeve commented on .github/workflows/CI.yml
> -            json: 'OFF'
Finally fixed this

2022-12-22 14:51 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +       "PrintFieldsInit": {
As much as having the list in the input file is kind of clunky and adds extra lines, I actually think I like it because you can see what all the options are and easily toggle them on or off. As opposed to having to go back into the README and remembering what the views were called and which ones can be printed

2022-12-29 01:26 UTC, MattRolchigo commented on src/CAparsefiles.cpp
> +    if (tinputdata["HTdeltax"] != nullptr) {
I replaces all of the nullptr comparisons with the "contains" member function

2022-12-29 01:27 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +   "TemperatureData": {
I think it's a lot easier to follow without the temperatures input files

2022-12-29 01:28 UTC, MattRolchigo commented
@streeve It looks like it's still failing on the json testing option

2023-01-03 15:55 UTC, streeve reviewed
Looks almost ready

2023-01-03 15:55 UTC, streeve commented on examples/Inp_AMBenchMultilayer.json
> +       "PrintIntermediateOutput": {
Should this be `PrintFieldsIntermediate`? And then (in a separate PR) allow choosing which fields to print just like the others? Potentially even removing the init/final options and relying entirely on the frequency of printing

2023-01-03 15:55 UTC, streeve commented on src/CAinterfacialresponse.hpp
> -        normalize(deltat, deltax);
Was this a bug?

2023-01-03 15:55 UTC, streeve commented on src/CAinitialize.cpp
> +void InputReadFromFile_json(int id, std::string InputFile, std::string &SimulationType, double &deltax, double &NMax,
That would let us avoid another rename when we remove the `old` versions

2023-01-03 15:55 UTC, streeve commented on src/runCA.cpp
> +        throw std::runtime_error("Error: attempted to parse json input file without ExaCA_ENABLE_JSON=ON");
Shouldn't this already be accounted for in `checkInputFileFormat`?

2023-01-03 15:55 UTC, streeve commented on unit_test/tstInit.cpp
> +    //  testInputReadFromFile(false);
Why is this commented?

2023-01-05 04:57 UTC, MattRolchigo commented on unit_test/tstInit.cpp
> +    TestDataFile << "      \"PrintFieldsFinal\": [\"UndercoolingCurrent\",\"GrainMisorientation\"]" << std::endl;
Yeah, we can have this test run for a "debug" case (all initial fields printed, final undercooling printed, grain misorientation and grainID/layerID printed) and for a "standard" case (grain misorientation and grainID/layerID printed, default ExaConstit output printed)

2023-01-05 05:04 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +       "PrintIntermediateOutput": {
The intermediate output is distinct from the init and final print options because it prints something other than just one field: it prints grain misorientation values for all cells that are non-liquid at that time step, and values of -1 for all liquid cells. Which is the reason it is named something slightly different. But I agree though that printing intermediate values of the other fields could be useful as well, the print options needs a few PR updates actually. They still don't work for runs with remelting, there's only 3 permutations of init fields that can be printed- "no debug", "light debug", and "full debug", and storing the options in a struct will simplify the code a lot

2023-01-05 05:06 UTC, MattRolchigo commented on src/CAinterfacialresponse.hpp
> -        normalize(deltat, deltax);
No, I just moved the call to normalize into the constructor itself (it is now on line 55), rather than have it called separately in each of `parseMaterialJson` and `parseMaterialOld`

2023-01-05 05:09 UTC, MattRolchigo commented on src/runCA.cpp
> +        throw std::runtime_error("Error: attempted to parse json input file without ExaCA_ENABLE_JSON=ON");
Yeah, that was just a redundant check I forgot to remove

2023-01-05 05:10 UTC, MattRolchigo commented on unit_test/tstInit.cpp
> +    //  testInputReadFromFile(false);
Because I'm dumb

2023-01-06 16:22 UTC, streeve reviewed
Few small things. Also, the capitalization of the new inputs is inconsistent, but I don't have a strong preference for which you choose. Are you going to add the analysis parsing here as well?

2023-01-12 20:16 UTC, streeve commented on examples/Inp_AMBenchMultilayer.json
> +       "HTdeltax": 5,
Good opportunity to make some of these variables more readable (HeatTransferDeltaX)

2023-01-12 20:23 UTC, streeve commented on examples/Inp_AMBenchMultilayer.json
> +      "S0": 25,
No idea what this is

2023-01-12 20:23 UTC, streeve commented on examples/Inp_AMBenchMultilayer.json
> +   "Nucleation": {
All of these are a bit unclear

2023-01-12 20:23 UTC, streeve commented on examples/Inp_AMBenchMultilayer.json
> +       "printExaConstitDefault": false,
Worth a separate ExaConstit subsection?

2023-01-12 20:35 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +       "printExaConstitDefault": false,
Maybe just "PrintExaConstitSize" where setting the size to 0 or not including the input tells the code not to print it (which is also what PrintIntermediateOutput does if Frequency = 0). Unlike PrintIntermediateOutput which has 2 inputs (the frequency of output and whether or not to print data between laser passes), this only has size as an input, so it didn't seem worthy of its own section.

2023-01-12 20:48 UTC, streeve commented on examples/Inp_AMBenchMultilayer.json
> +       "printExaConstitDefault": false,
Not sure how you use one input for both default size and to turn it off. This would add an easy way to turn it off (without removing entirely)
```
"ExaConstitRVE"
{
  "Print": false,
  "Default": false,
  "LengthMicrons": 10,
}
```

2023-01-12 20:57 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +       "printExaConstitDefault": false,
There wouldn't be a default size in this case, a size would just always be required and if no size is given, nothing is printed. The default size is kind of arbitrary considering that we picked it based on what we wanted for the AMBench runs but wouldn't be all that useful for anyone else. It just seems like such a rarely used feature for most users to necessitate its own section

2023-01-12 21:00 UTC, streeve commented on examples/Inp_AMBenchMultilayer.json
> +       "printExaConstitDefault": false,
Fair enough

2023-01-12 22:12 UTC, MattRolchigo commented
Title updated to reflect that the analysis input file formatting will be in a separate PR

2023-01-17 21:14 UTC, streeve reviewed
Sorry I wasn't clear in the last two places. Other than those and updating the readme I think it's ready

2023-01-17 21:18 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> +   "RandomSeed": 0,
Yeah I realized I'm being inconsistent with it as-is, the random seed is stored as a double in the code, but when it's used in a function, that function requires the seed to be an int so it must just automatically be getting converted. We should probably should make a new issue about that...

2023-01-17 21:19 UTC, MattRolchigo commented on examples/Inp_AMBenchMultilayer.json
> -      "MeanUndercooling": 5,
Probably not, now that I think about it... I was just wanting to keep it consistent with StDev, but at least one of the two should have Undercooling in there so that we know what the distribution actually is

2023-01-20 16:59 UTC, streeve approved these changes
Looks good to me

2023-01-20 22:43 UTC, merged