Helper functions and analysis print routine rewrite
LLNL/ExaCA pull request #167
Opened 2023-01-23 15:58 UTC by MattRolchigo

* Separate calculations into separate helper functions (previously parts of print subroutines in GAprint.cpp)
* Printing grain-wise statistics to a single file, edited by multiple print routines, rather than to individual files
* Keep old calculated quantities that are no longer used with warnings that they will not be computed in a future release

2023-01-25 19:27 UTC, streeve reviewed
Haven't looked close yet, but there's a conflict anyway

2023-01-25 19:27 UTC, streeve commented on analysis/unit_test/tstKokkosUtils.hpp
> +void testgetRepresentativeRegionGrainIDs() {
Can you add top level test comments? Just not initially sure what the setup/intent is

2023-01-25 19:27 UTC, streeve commented on analysis/src/GAprint.cpp
> +    std::cout << "Note: lines that start with *** are information that will no longer be collected/printed to the "
Why not just add a line with "Warning: the analysis is deprecated and will be removed" before each old section? Not sure about motivation for the pseudo comment *** here

2023-01-25 19:27 UTC, streeve commented on analysis/src/GAprint.cpp
> +void PrintBuiltTransAspectRatioData(std::ofstream &QoIs, std::ofstream &GrainStatistics, std::vector<int> GrainExtentX,
Would rather keep `printBuiltTransverseAspectRatio`. I don't think every function needs `Data` at the end and would rather a long name than shortening something like `Trans`

2023-01-25 19:27 UTC, streeve commented on analysis/src/GAprint.cpp
> +void PrintSizeData(bool PrintStats, std::ofstream &QoIs, std::ofstream &GrainStatistics,
`printGrainSize`?

2023-01-26 14:14 UTC, MattRolchigo commented on analysis/unit_test/tstKokkosUtils.hpp
> +void testgetRepresentativeRegionGrainIDs() {
Added a comment before each unit in analysis/unit_test briefly describing what each test does

2023-01-30 16:45 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +        int MinCoord = *min_element(GrainCoordinate.begin(), GrainCoordinate.end());
Consistency with what I did in src/CAparsefiles.cpp `parseTemperatureCoordinateMinMax` I guess

2023-02-08 21:07 UTC, streeve requested changes
Last changes I think

2023-02-08 21:07 UTC, streeve commented on analysis/src/GAutils.cpp
> +                                 const int NumberOfGrains, double deltax, std::string RegionType) {
Same here - can't you assume the size of `UniqueGrainIDVector` is the number of grains?

2023-02-08 21:15 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +                                 const int NumberOfGrains, double deltax, std::string RegionType) {
You mean not passing NumberOfGrains as an argument since it's the same as the size of UniqueGrainIDVector?

2023-02-08 21:35 UTC, streeve commented on analysis/src/GAutils.cpp
> +    NumberOfGrains = UniqueGrainIDVector.size();
Confused here since it is inside `getUniqueGrains`, but no strong feelings on the separate variable/size

2023-02-08 21:35 UTC, streeve commented on analysis/src/GAutils.cpp
> +                                 const int NumberOfGrains, double deltax, std::string RegionType) {
Yes, but it sounds like you'd prefer to

2023-02-08 21:37 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +    NumberOfGrains = UniqueGrainIDVector.size();
`getUniqueGrains` also has the line `NumberOfGrains = UniqueGrainIDVector.size();` inside of it, `NumberOfGrains` is passed uninitialized by reference into `getUniqueGrains` to avoid setting it to the wrong thing outside the function where the unique grain IDs are obtained

2023-02-09 16:37 UTC, streeve approved these changes

2023-02-09 17:06 UTC, merged