Print and parse log files with json format
LLNL/ExaCA pull request #169
Opened 2023-01-27 16:20 UTC by MattRolchigo

Prints log files as json if json is enabled (otherwise using old format). Maintains capability to read log files of previous formats

2023-01-27 20:23 UTC, streeve requested changes

2023-01-27 20:23 UTC, streeve commented on analysis/src/GAutils.cpp
> +    std::cout << "Warning: old (non-json) form of log file detected; compatibility with analyzing these data sets will "
Remove (already in check format)

2023-01-27 20:23 UTC, streeve commented on src/CAprint.cpp
> +        ExaCALog << irf.print_old() << std::endl;
`print_Old` everywhere else

2023-01-27 20:23 UTC, streeve commented on analysis/src/GAutils.cpp
> +    // Ensure that form of log file (.log or .json) matches the compilation option used to generate it
But there's no guarantee that you're analyzing something created from the same build of ExaCA. It seems like the issue is really that you used to add the `.log` and now you're not sure which one exists

2023-01-30 15:01 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +    // Ensure that form of log file (.log or .json) matches the compilation option used to generate it
Yeah for running `grain_analysis` (where the input file is required, and the name of the log file including the extension is required), it should just require that the log file from the input file matches the actual log file. For running `grain_analysis_amb` (no input file used), I guess it can just check for one, then check for the other

2023-01-30 15:54 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +    // Ensure that form of log file (.log or .json) matches the compilation option used to generate it
Actually, the problem with that is that the analysis file has a hardcoded filename that is either json or log - so it'll fail in the CI if it's being tested with one and the extension used is the other. So I guess I'll just have it check for both

2023-01-30 21:54 UTC, streeve reviewed
Comment/warning changes. Otherwise ready to go

2023-01-30 21:54 UTC, streeve commented on analysis/src/runGA_AMB.cpp
>          BaseFileName = argv[1];
Better to redefine the command line arg to include the file ending?

2023-01-30 21:54 UTC, streeve commented on src/runCA.cpp
> +        std::cout << "Warning: log file printed using non-json format - ExaCA_ENABLE_JSON=ON will be required in a "
"JSON will be required in a future release" - I assume we'll remove the CMake option at the same time

2023-01-30 21:54 UTC, streeve commented on analysis/src/GAutils.cpp
> +// Check if log file format is consistent with compilation option, swap form if necessary
"is consistent with input, swap form if necessary. FIXME: Should be removed in a future release"

2023-01-30 22:04 UTC, MattRolchigo commented on analysis/src/runGA_AMB.cpp
>          BaseFileName = argv[1];
Well the command line argument is also used to find the .vtk file, so having .json or .log be required there might be a little strange. But maybe we should require an extra command line arg that specifies if the data to be read uses .json or .log format, defaulting to .log if not given

2023-01-30 22:48 UTC, streeve commented on analysis/src/GAutils.cpp
> +            LogFileUpdate = LogFileNamePrefix + ".json";
This will break if you run the old version after outputting with the new, right?

2023-01-30 22:48 UTC, streeve commented on analysis/src/runGA_AMB.cpp
>          BaseFileName = argv[1];
Forgot about that. Should be able to use the same function as the main analysis to try either one (or only txt if json isn't enabled)

2023-01-30 22:52 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +            LogFileUpdate = LogFileNamePrefix + ".json";
You mean if I have output of both types in a directory and I run it without json enabled, and it goes to read the .json file?

2023-02-01 16:17 UTC, streeve reviewed
Last question

2023-02-01 16:17 UTC, streeve commented on analysis/src/GAutils.cpp
> +        LogFile = OptionalFilesRead[0] + ".log";
Check this exists?

2023-02-01 16:17 UTC, streeve commented on src/runCA.cpp
> +        std::cout << "Warning: JSON will be required in a future release" << std::endl;
Not clear this warning is coming from the log file format

2023-02-01 16:33 UTC, MattRolchigo commented on analysis/src/runGA_AMB.cpp
> +        bool Json_found = checkFileExists(LogFile, 0, false);
We do that later for both cases. Here, we're saying there's 2 possibilities: JSON is enabled, or JSON is not enabled. If JSON is enabled, we can use either a JSON or a .log file, and JSON is preferred. So we check if the JSON file exists and if it isn't, the .log file should exist. If JSON is not enabled, we don't care if there is a JSON file, but the .log file should exist. At this point, there's only 1 possibility for the file extension that should exist. We call `CheckInputFiles` and check if that exists, and throw an error if it doesn't.

2023-02-01 16:36 UTC, MattRolchigo commented on analysis/src/GAutils.cpp
> +        LogFile = OptionalFilesRead[0] + ".log";
7 and 8 lines after this, we check if the file is empty or not, which accomplishes the same thing

2023-02-01 17:00 UTC, streeve approved these changes

2023-02-01 20:25 UTC, merged