Json format for analysis input files
LLNL/ExaCA pull request #175
Opened 2023-02-23 20:53 UTC by MattRolchigo

2023-02-23 20:56 UTC, MattRolchigo commented
Still need to update the README. Also, @streeve , running the analysis script now requires two command line inputs instead of one, theoretically should the workflow test both cases? We have the line 

`$HOME/exaca/bin/grain_analysis AnalyzeSmallDirS.txt`

In the CI, which still works without JSON, but when running with JSON it should be

`$HOME/exaca/bin/grain_analysis AnalyzeSmallDirS.json TestProblemSmallDirS`

2023-02-23 22:35 UTC, streeve reviewed
For the CI, you can add a copy of the "Test GA" section with `if: ${{ matrix.input == "json" }}` and the new extra commandline arg version

2023-02-23 22:35 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +#ifdef ExaCA_ENABLE_JSON
Seems superfluous (can just use the one above)

2023-02-23 22:35 UTC, streeve commented on analysis/examples/AnalyzeAMB.json
> +[
I would wrap this in a top level `{}` and name this list `Regions` or something in case you want to add other things later. Or maybe these inputs should separate total, sub-volumes, planes, etc.? It's not really clear to me what each of these is on first glance

2023-02-23 22:35 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +    double regionSize_Meters;
Why both units?

2023-02-23 22:35 UTC, streeve commented on analysis/examples/AnalyzeAMMT.txt
> +Used in post-processing script to analyze select ExaCA outputs
Was this intentionally added?

2023-02-23 22:35 UTC, streeve commented on analysis/src/runGA.cpp
> +            throw std::runtime_error("Error: Full path to and name of analysis file and microstructure data must be "
"microstructure base name"?

2023-02-27 17:51 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +    double regionSize_Meters;
Since the conversion from meters to cells depends on the dimensions of the region (meters, square meters, or cubic meters), and there's situations where both are needed, it made sense to store both representations instead of converting multiple times

2023-02-27 17:52 UTC, MattRolchigo commented on analysis/examples/AnalyzeAMMT.txt
> +Used in post-processing script to analyze select ExaCA outputs
Nope, that's a mistake. So was AnalysisCA5.txt

2023-02-28 08:00 UTC, streeve commented on .github/workflows/CI.yml
> +          if: ${{ matrix.input == "json" }}
```suggestion
          if: ${{ matrix.input == 'json' }}
```

2023-02-28 08:00 UTC, streeve commented on .github/workflows/CI.yml
> +             $HOME/exaca/bin/ExaCA-Kokkos ../../examples/Inp_SmallDirSolidification.${{ matrix.input }} 
Can just be `.json`

2023-02-28 14:16 UTC, MattRolchigo commented on .github/workflows/CI.yml
> +          if: ${{ matrix.input == "json" }}
@streeve tried that, still getting a syntax error. The weird thing is, line 108 where it claims the error is is identical to line  104. I've never used yaml before so I have no idea what's going on here

2023-03-06 13:50 UTC, streeve commented on analysis/README.md
> +| Option                | Allowed arrays                | Details
Output | Compatible options | Details?

2023-03-06 13:50 UTC, streeve commented on analysis/unit_test/tstRepresentativeRegion.hpp
> +void testConstructRepresentativeRegion_Volume() {
These are more testing the parsing (still useful), but not the analysis itself, right?

2023-03-09 02:34 UTC, MattRolchigo commented on analysis/unit_test/tstRepresentativeRegion.hpp
> +void testConstructRepresentativeRegion_Volume() {
Yeah, they test the constructor of the RepresentativeRegion struct from analysis/src/GArepresentativeregion.hpp, which is why I used this as the name. Wasn't sure if a separate file just for testing the constructor and then a different one for testing the member functions made sense

2023-03-09 02:51 UTC, MattRolchigo commented on analysis/examples/AnalyzeDirS.json
> +{
Fixed (line 2 of the file)

2023-03-13 16:09 UTC, streeve commented on .github/workflows/CI.yml
> +          if: ${{ matrix.input == "json" }}
Fixed - it was some non-standard character

2023-03-13 16:23 UTC, streeve commented on .github/workflows/CI.yml
> +        if: ${{ matrix.input == 'json' }}
Shouldn't this be the single case for "txt"?

2023-03-13 16:23 UTC, streeve commented on .github/workflows/CI.yml
> -          $HOME/exaca/bin/grain_analysis AnalyzeSmallDirS.txt
Should be the JSON case (not removed)?

2023-03-30 17:18 UTC, streeve requested changes
Nothing major. Worth considering just passing the full region object to all these methods - upside is you don't have to pass all the separate values around all the time; downside those methods are then directly tied to the regions

2023-03-30 17:18 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +    void GetRegionTypeOrientation() {
Isn't this a `set` method?

2023-03-30 17:18 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +            throw std::runtime_error("Error: Invalid region type in GetRegionSize during region construction");
Isn't this set internally?

2023-03-30 17:18 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +    void GetRegionSize(double deltax) {
Again, isn't this a `set` method?

2023-03-30 17:18 UTC, streeve commented on analysis/src/runGA.cpp
> +        Kokkos::initialize();
Why not initialize once?

2023-03-30 17:18 UTC, streeve commented on analysis/src/runGA.cpp
> +                        QoIs, representativeRegion.xBounds_Cells[0], representativeRegion.xBounds_Cells[1],
You pass the individual components a lot - maybe just pass the arrays?

2023-04-03 12:41 UTC, MattRolchigo commented on analysis/src/runGA.cpp
> +                        QoIs, representativeRegion.xBounds_Cells[0], representativeRegion.xBounds_Cells[1],
That was done so that the same subroutines could be used with and without the "new" analysis, since the old analysis input read does not create a `representativeRegion` object. I'm planning on passing the full object in the future, I'll go back and mark these spots as TODO after removing the old analysis options in version 1.2

2023-04-03 12:52 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +    void GetRegionTypeOrientation() {
What do you mean? I don't have any methods with "set" in the title, all the subroutines that calculate or return a specific thing all start with the word "get"

2023-04-03 12:53 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +            throw std::runtime_error("Error: Invalid region type in GetRegionSize during region construction");
Yeah, but without it, I get a warning about `regionSize_Microns` may be uninitialized when `if` statements are false

2023-04-03 16:54 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +    void GetRegionTypeOrientation() {
Noting from our conversation that `set` makes more sense here from the perspective of class data

2023-04-03 17:19 UTC, streeve reviewed
Pretty sure this is the last round

2023-04-03 17:19 UTC, streeve commented on analysis/src/GAprint.cpp
> +void writeIPFColoredCrossSection(std::string BaseFileNameThisRegion, RepresentativeRegion representativeRegion,
I think it may be worth making these class methods of the region now since they already don't work with the older version

2023-04-03 17:19 UTC, streeve commented on analysis/src/runGA.cpp
> +#endif
Need an `#else` to print out in case JSON isn't enabled?

2023-04-03 17:28 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +                if (Units == "Meters") {
I think everything that takes a string, sets values, and errors if invalid should be a separate member function (here `checkUnits`)

2023-04-03 17:31 UTC, MattRolchigo commented on analysis/src/GAprint.cpp
> +void printAnalysisHeader_Volume_Old(std::ofstream &QoIs, const int XLow, const int XHigh, const int YLow,
All of the routines with "_Old" in them are going to be removed after the release anyways, since more relevant/better organized stats are printed via the other routines

2023-04-03 17:32 UTC, MattRolchigo commented on analysis/src/GAprint.cpp
> +void writeIPFColoredCrossSection(std::string BaseFileNameThisRegion, RepresentativeRegion representativeRegion,
Makes sense - so once the older version is removed, does it make sense for GAprint to be added to GArepresentativeregion entirely?

2023-04-03 17:35 UTC, MattRolchigo commented on analysis/src/runGA.cpp
> +#endif
In this case no, it's taken care of via the if block on lines 234-235

2023-04-03 17:40 UTC, streeve commented on analysis/src/runGA.cpp
> +#endif
But if it's json output from a previous run that is then analyzed with a non-json exe it would do nothing, right?

2023-04-03 17:40 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +                if (Units == "Meters") {
There's a lot of sections of code that look similar to this, but none of them really do the exact thing (though there's. definitely some redundancy with `printMeanSize`)

2023-04-03 17:42 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +                if (Units == "Meters") {
Agree, but even without reuse I think it will be easier to read splitting them out

2023-04-03 17:44 UTC, MattRolchigo commented on analysis/src/runGA.cpp
> +#endif
Oh yeah, good point, there should be an error thrown in that case

2023-04-03 19:08 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +    // TODO: Consolidate volume/area header print routines from GAprint when non-JSON option is removed
Not needed anymore?

2023-04-03 19:10 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +    // TODO: Consolidate volume/area header print routines from GAprint when non-JSON option is removed
No, that's reminding me that the code in `printAnalysisHeader_Volume` and the code in the very similar print area routine that's still in GAprint.cpp as it is used with both file formats can be combined

2023-04-03 19:16 UTC, streeve commented on analysis/src/GAprint.cpp
> +void printAnalysisHeader_Area(std::ofstream &QoIs, const int XLow_cells, const int XHigh_cells, const int YLow_cells,
Also _Old?

2023-04-03 19:16 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +                if (Units == "Meters") {
Now that I read this again, can't you check for valid units one time first, then do one `if` block for the 4 bounds options? If you separate the cell vs meters into yet more smaller functions you can call them in either order to simplify more

2023-04-03 19:20 UTC, MattRolchigo commented on analysis/src/GAprint.cpp
> +void printAnalysisHeader_Area(std::ofstream &QoIs, const int XLow_cells, const int XHigh_cells, const int YLow_cells,
Not _Old, used by both

2023-04-04 19:42 UTC, streeve reviewed
Made some small changes and think I found a bug?

2023-04-04 19:42 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +            for (int i = 0; i < 2; i++) {
<=

2023-04-04 19:44 UTC, streeve approved these changes
Anything else I would suggest can wait until things are cleaned up after the release

2023-04-04 22:25 UTC, merged