Separate GrainID components for sending/receiving halo data as floats
LLNL/ExaCA pull request #180
Opened 2023-04-03 00:53 UTC by MattRolchigo

Performance improvement by using `float` instead of `double` for send and receive buffers. Previously, this was not possible as GrainID values with magnitudes larger than 16,777,215 could not be precisely converted to `float` and back to `int` - but by separating the GrainID values sent into 2 components (a " unique orientation" and a "grain repeat number"), these 2 components could be converted to float values, be sent/received, and combined again back into a GrainID. For example, a GrainID of 20,001,123 in a simulation with 10,000 unique grain orientations would have a "unique orientation" of 1,123 and a "grain repeat number" of 2,000 - and while 20,001,123 may not be able to be converted to `float` and back to `int` without issues, 1,123 and 2,000 both can be.

2023-04-04 19:00 UTC, streeve requested changes

2023-04-04 19:00 UTC, streeve commented on src/CAupdate.cpp
> -                                    double GhostGID = static_cast<double>(h);
Future plan from our discussion: mark this cell ID for comm and do it separately (also true for the nucleation case below)

2023-04-04 19:51 UTC, MattRolchigo commented on unit_test/tstKokkosInitMPI.hpp
> +    // Changed number of orientations to avoid overlap with testFillSteeringVector_Remelt (which used NGrainOrientations
Yeah, I guess it's useful for the two tests to test different values for NGrainOrientations, but it isn't related to this change set

2023-04-04 19:57 UTC, MattRolchigo commented on unit_test/tstKokkosUpdate.hpp
> +void testConvertGrainIDForBuffer() {
This seems to me to cover a pretty wide range of GrainID conversions, 3 values below NGrainOrientations, 3 values above NGrainOrientations including the one just below 2*NGrainOrientations, and the corresponding negative GrainIDs. What other cases are worth testing? Maybe a really large GrainID, like one of the ones that previously would've been too large for accurate conversion?

2023-04-04 20:09 UTC, streeve commented on unit_test/tstKokkosUpdate.hpp
> +void testConvertGrainIDForBuffer() {
Just an idea - you know better than I do. Your last thought seems useful

2023-04-04 20:10 UTC, MattRolchigo commented on src/CAupdate.cpp
> -                                    double GhostGID = static_cast<double>(h);
Added a comment about this to the line above this

2023-04-04 20:43 UTC, MattRolchigo commented on unit_test/tstKokkosUpdate.hpp
> +void testConvertGrainIDForBuffer() {
I added to the test (and also made it more easy to add to it in the future if we decide we need to)

2023-04-10 19:48 UTC, MattRolchigo commented
@streeve this should be good to go now

2023-04-10 20:36 UTC, streeve commented
> this should be good to go now

Do you have performance numbers?

2023-04-12 17:49 UTC, streeve approved these changes

2023-04-12 17:51 UTC, merged