Reduce size of send/recv buffers for communication
LLNL/ExaCA pull request #183
Opened 2023-04-17 19:01 UTC by MattRolchigo

Reduced buffer size by using an initial guess (rather than using the max possible size as done previously), and new views to track the number of cells with associated data contained in the buffer. If a rank exceeds the buffer's max capacity, a resize of the buffers is performed across all ranks

2023-04-21 14:54 UTC, streeve requested changes

2023-04-21 14:54 UTC, streeve commented on src/CAghostnodes.cpp
> +        Kokkos::resize(BufferNorthSend, NewBufSize, 8);
You don't need the previous values do you?

2023-04-21 14:54 UTC, streeve commented on src/CAghostnodes.cpp
> +        int padded_capacity_percent = round(0.1 * needed_buffer_capacity);
Would be good to make this a function arg with a default

2023-04-21 14:57 UTC, MattRolchigo commented on src/runCA.cpp
>                  CellTypeInit_Remelt(nx, MyYSlices, LocalActiveDomainSize, CellType, CritTimeStep, id, ZBound_Low);
What do you mean? The cell type init with remelting doesn't require accessing the halo regions as no active cells are created (melting has no occurred yet, so there is no solid-liquid interface, unlike the "no remelt" case where cells with temperature data may be initialized as liquid)

2023-04-21 14:59 UTC, MattRolchigo commented on src/runCA.cpp
> +            BufSize = ResizeBuffers(BufferNorthSend, BufferSouthSend, BufferNorthRecv, BufferSouthRecv, SendSizeNorth,
What resize+optional second resize? There's only one resize here

2023-04-21 15:01 UTC, MattRolchigo commented on src/CAupdate.cpp
> -                CellType(GlobalD3D1ConvPosition) = Active;
If np = 1, the cell type is still changed to active. If np > 1, the cell type only becomes active if the buffer load was successful, otherwise it is changed into a new temporary type ActiveFailedBufferLoad to mark it

2023-04-21 15:02 UTC, MattRolchigo commented on src/CAghostnodes.cpp
> +        Kokkos::resize(BufferNorthSend, NewBufSize, 8);
I actually do - RefillBuffers doesn't overwrite the existing buffer data, it only fills the new buffer data with the information from the cells of type ActiveFailedBufferLoad

2023-04-21 15:40 UTC, streeve commented on src/runCA.cpp
> +            BufSize = ResizeBuffers(BufferNorthSend, BufferSouthSend, BufferNorthRecv, BufferSouthRecv, SendSizeNorth,
Sorry, resize+optional refill if needed

2023-04-21 16:25 UTC, streeve commented on src/runCA.cpp
> +            BufSize = ResizeBuffers(BufferNorthSend, BufferSouthSend, BufferNorthRecv, BufferSouthRecv, SendSizeNorth,
But neither are inlined?

2023-04-21 16:42 UTC, MattRolchigo commented on src/runCA.cpp
> +            BufSize = ResizeBuffers(BufferNorthSend, BufferSouthSend, BufferNorthRecv, BufferSouthRecv, SendSizeNorth,
But RefillBuffers calls loadghostnodes which is inlined

2023-04-25 13:48 UTC, streeve reviewed
I added comments in the old tests, but then remembered the new test - somewhere a test should start with a buffer larger than needed and then run again with one smaller than needed

2023-04-25 13:48 UTC, streeve commented on src/CAghostnodes.cpp
> +        int padded_capacity = floor(0.1 * MaxBufSize);
10% of max seems too big

2023-04-26 19:20 UTC, MattRolchigo commented on unit_test/tstKokkosInitMPI.hpp
> +    int BufSize = nx * nzActive;
We test the case where the buffer isn't large enough in testResizeRefillBuffers, the init tests take care of the case where the buffers are larger than needed

2023-04-28 18:27 UTC, streeve commented on src/CAghostnodes.cpp
> +        NewBufSize = OldBufSize + needed_buffer_capacity + numcells_buffer_padding;
```suggestion
        NewBufSize = max_count_global + numcells_buffer_padding;
```

2023-04-28 18:27 UTC, streeve commented on src/CAghostnodes.cpp
> +    return NewBufSize;
Why return?

2023-04-28 18:27 UTC, streeve commented on src/CAghostnodes.cpp
> +        if (NewBufSize > MaxBufSize)
Not sure it's worth tracking the max size - even if you exceed it (which I can't imagine) it wouldn't hurt anything

2023-04-28 18:27 UTC, streeve commented on src/CAghostnodes.cpp
> +                  ViewI_H SendSizeSouth_Host, int OldBufSize, int MaxBufSize, int numcells_buffer_padding) {
`BufferPadding`? Not sure of the change in style

2023-05-01 14:00 UTC, MattRolchigo commented on src/CAghostnodes.cpp
> +    return NewBufSize;
I believe this was to be able to call this subroutine without BufSize being specified, and allowing BufSize to be reset to the default value. But this is a confusing place to do this

2023-05-01 14:07 UTC, MattRolchigo commented on src/CAghostnodes.cpp
> +        if (NewBufSize > MaxBufSize)
Yeah, and if we ever reach it, something probably went very wrong...

2023-05-02 21:21 UTC, streeve approved these changes
I think this is ready. The separate buffer refill when the count is exceeded makes me want to completely remove the buffer loading from cell capture, but that should be a separate PR to understand the performance implications vs better design

2023-05-03 00:43 UTC, merged