Consolidated analysis functions in GArepresentativeregion
LLNL/ExaCA pull request #198
Opened 2023-05-16 14:05 UTC by MattRolchigo

With removal of non-JSON functions, consolidated functions calculating quantities and writing out quantities from the representative region inside of the class. Updated the unit test accordingly

2023-05-16 15:31 UTC, streeve requested changes
First round

2023-05-16 15:31 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +    std::vector<int> getUniqueGrains(const std::vector<int> GrainIDVector, int &NumberOfGrains) {
Not sure I see why this should be a member function - it's not using any member data and returns new information that's not stored

2023-05-16 15:31 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +    void calcGrainExtent(std::vector<float> &GrainExtent, ViewI3D_H GrainID, const std::vector<int> UniqueGrainIDVector,
I think overall, moving these into the struct should mean storing more internally and not requiring the main analysis functions to keep things at the top level scope. I think `GrainExtent` can be stored internally and used in other functions below (or if not and it doesn't make sense for this function I do think it will for at least a couple)

2023-05-17 13:17 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +    void calcGrainExtent(std::vector<float> &GrainExtent, ViewI3D_H GrainID, const std::vector<int> UniqueGrainIDVector,
I agree for `GrainIDVector`, `UniqueGrainIDVector`, and `GrainSizeVector_Microns` since they are used exclusively in multiple other member functions, but `GrainExtent` is a little different because it takes awhile to compute and I try to avoid calculating it unless required. It also isn't used in other member functions other than printGrainExtent and printAspectRatio.

2023-05-17 15:17 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +    std::vector<int> getUniqueGrains(const std::vector<int> GrainIDVector, int &NumberOfGrains) {
A few of the vectors commonly used in the member functions were added to the RepresentativeRegion struct

2023-06-03 19:03 UTC, MattRolchigo commented on analysis/src/runGA.cpp
>              if ((representativeRegion.AnalysisOptions_StatsYN[3]) ||
I did this, just didn't show up as a change for some reason

2023-06-03 19:04 UTC, MattRolchigo commented on analysis/unit_test/tstUtils.hpp
> +TEST(TEST_CATEGORY, grain_util_tests) {}
Maybe eventually if I have a bunch of free time at some point

2023-06-13 20:12 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +        // If representativeRegion.AnalysisOptions_StatsYN[3] or
That's partially thanks to the formatting combining lines

2023-06-13 20:12 UTC, MattRolchigo commented on analysis/src/GArepresentativeregion.hpp
> +    void printAnalysisHeader(std::ofstream &QoIs, const std::string regionName) {
Yeah I guess I could have a copy of it inside the class too

2023-06-22 19:49 UTC, streeve requested changes

2023-06-22 19:49 UTC, streeve commented on analysis/src/GAutils.cpp
> +void dual_print(std::string temp, std::ostream &stream1, std::ostream &stream2) {
Can you call this `output` or `text` (also in the struct)? I can't help but assume that `temp` is temperature

2023-06-22 19:49 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +        // representativeRegion.AnalysisOptions_PerGrainStatsYN[2] is toggled, X extents are needed If
```suggestion
        // If option 3 or 5 is on, grain extents are needed
        // If option 4 or 2 is on, X extents are needed
```
I should have been more clear, I really just meant that the extra text doesn't help the comment and also causes the issues with auto-formatting

2023-06-26 21:21 UTC, streeve commented on analysis/src/GArepresentativeregion.hpp
> +        // representativeRegion.AnalysisOptions_PerGrainStatsYN[2] is toggled, X extents are needed If
Changed somewhere else, but not here

2023-06-26 21:22 UTC, streeve commented on analysis/src/GAutils.cpp
> +void dual_print(std::string temp, std::ostream &stream1, std::ostream &stream2) {
Changed here, but not in the class

2023-06-29 16:24 UTC, streeve approved these changes

2023-06-30 13:34 UTC, merged