Nucleation data object to organize associated constants and Views
LLNL/ExaCA pull request #213
Opened 2023-06-20 14:56 UTC by MattRolchigo

Also rewrote unit tests to use the nucleation structure, otherwise this basically just moved existing functions into the new file CAnucleation.hpp

2023-06-21 14:03 UTC, streeve requested changes

2023-06-21 20:30 UTC, MattRolchigo commented on src/runCA.cpp
> +    nucleation.placeNuclei(MaxSolidificationEvents, NumberOfSolidificationEvents, LayerTimeTempHistory, RNGSeed, 0, nx,
The problem is that `NMax`, `dTN`, and `dTsigma` are read in `InputReadFromFile`, at which point we don't have enough information to construct the Nucleation class (the Nucleation class is constructed later, once those parameters have been read and stored). My current plan is for those three variables to be part of an inputs class. Then, once the code is entirely reorganized into structs, I can have the general inputs defined in an Inputs class, with classes like Print and Nucleation inheriting the relevant inputs

2023-06-21 20:34 UTC, MattRolchigo commented on unit_test/tstKokkosInitMPI.hpp
>      using memory_space = Kokkos::DefaultExecutionSpace::memory_space;
using memory_space = TEST_MEMSPACE?

2023-06-21 20:36 UTC, streeve commented on unit_test/tstKokkosInitMPI.hpp
>      using memory_space = Kokkos::DefaultExecutionSpace::memory_space;
Yeah that works for me

2023-06-22 13:20 UTC, streeve approved these changes

2023-06-22 17:41 UTC, streeve commented on src/runCA.cpp
> +    nucleation.placeNuclei(MaxSolidificationEvents, NumberOfSolidificationEvents, LayerTimeTempHistory, RNGSeed, 0, nx,
I think we're mostly on the same page here and it's fair to push this off until later

2023-06-22 18:03 UTC, merged