WIP: CellData struct for celltype, grainid, layerid, with subviews
LLNL/ExaCA pull request #215
Opened 2023-06-23 21:06 UTC by MattRolchigo

- Moved cell type/substrate init/layer init subroutines into CellData struct
- Consolidated cell data init unit tests
- Used subviews for portions LayerID, GrainID, CellType, where the subviews are indexed with respect to a layer, not the whole domain

Currently either deadlocking (or really slow) on GPU backends, not ready to merge yet

2023-06-26 21:36 UTC, streeve requested changes
First read-through

2023-06-26 21:36 UTC, streeve commented on src/CAcelldata.hpp
> +        , GrainID(view_type_int(Kokkos::subview(GrainID_AllLayers, std::make_pair(0, LocalActiveDomainSize))))
This is constructing new views from subviews of the `AllLayers` view - I'm pretty sure you just want the subviews stored or potentially to use subviews as temporaries and/or return subviews from class methods

2023-06-26 21:36 UTC, streeve commented on src/CAcelldata.hpp
> +        if (SimulationType == "C")
I think this is the right time to create separate classes for DS and non-DS problems. Probably with a shared base class

2023-06-26 21:36 UTC, streeve commented on src/CAghostnodes.cpp
> +                int CellCoordinateSouth = k * nx * MyYSlices + i * MyYSlices + 1;
Can you put this indexing in the class too?

2023-06-26 21:36 UTC, streeve commented on src/CAcelldata.hpp
> +        auto GrainID_local = GrainID;
Yeah, just create the subviews here instead of storing them

2023-06-26 21:36 UTC, streeve commented on src/CAcelldata.hpp
> +        int BottomOfCurrentLayer = ZBound_Low * nx * MyYSlices;
I would make these member variables so you can always make the right subview as needed

2023-06-29 18:54 UTC, streeve commented on src/CAghostnodes.cpp
> +                int CellCoordinateSouth = k * nx * MyYSlices + i * MyYSlices + 1;
You already explained this is specific to the ghosts

2023-06-29 19:00 UTC, MattRolchigo commented on src/CAcelldata.hpp
> +        if (SimulationType == "C")
I still think that it'll be easier to do this once the rest of the code is organized into structs (particularly the inputs, which is probably the first class that should be organized into base + problem-specific data)

2023-07-06 17:10 UTC, streeve requested changes

2023-07-06 17:10 UTC, streeve commented on src/CAcelldata.hpp
> +    int get_baseplate_size_z(int nz, double *ZMaxLayer, double ZMin, double deltax, int LayerHeight,
Worth considering if this belongs here if it doesn't use any member variables

2023-07-06 17:10 UTC, streeve commented on src/CAghostnodes.cpp
> +    ViewI CellType = cellData.getCellTypeSubview();
Would use `auto` once the class is templated

2023-07-06 17:25 UTC, MattRolchigo commented on src/CAcelldata.hpp
> +    int get_baseplate_size_z(int nz, double *ZMaxLayer, double ZMin, double deltax, int LayerHeight,
I think it does, it's exclusively used by functions within celldata.hpp

2023-07-06 17:31 UTC, streeve commented on src/CAcelldata.hpp
> +    int get_baseplate_size_z(int nz, double *ZMaxLayer, double ZMin, double deltax, int LayerHeight,
Well I clearly read too fast then, but in that case it's worth storing some of these things in the class instead of passing them around

2023-07-06 17:34 UTC, MattRolchigo commented on src/CAcelldata.hpp
> +    int get_baseplate_size_z(int nz, double *ZMaxLayer, double ZMin, double deltax, int LayerHeight,
Yeah this is a weird function because all of the inputs would theoretically be part of a future grid class, but this function itself is only going to be used by CellData

2023-07-06 18:28 UTC, MattRolchigo commented on src/CAcelldata.hpp
> +    using view_type_int_host = Kokkos::View<int *, layout, Kokkos::HostSpace>;
But then won't I have to do `using host_view_type = typename device_view_type::HostMirror;` every time I need it for whatever kind of view?

2023-07-06 18:34 UTC, streeve commented on src/CAcelldata.hpp
> +    using view_type_int_host = Kokkos::View<int *, layout, Kokkos::HostSpace>;
You can put that here as a class typedef

2023-07-06 18:37 UTC, streeve commented on src/CAcelldata.hpp
> +    using view_type_int_host = Kokkos::View<int *, layout, Kokkos::HostSpace>;
And actually, we should replace what we have in the nucleation class with the same (it currently uses the top-level `layout`, but doesn't really need to)

2023-07-07 16:48 UTC, streeve reviewed
I may have missed more `auto` as well. I think this is ready, but I'm a bit concerned that I may have broken real problems, like with the unmanaged View

2023-07-07 17:40 UTC, MattRolchigo commented
If you think the unmanaged view might give us problems we can roll back that commit since it isn't a related change to this PR, that part of the code was all just copied and pasted from CAinitialize.cpp

2023-07-10 14:16 UTC, MattRolchigo commented
@streeve seems like the unmanaged view was fine, but I had an unrelated bug in the intermediate misorientation output function. Should be good to go now

2023-07-10 18:55 UTC, streeve commented
I need to take one more quick look, but I think this should wait on #217 to make sure I don't make similar mistakes again here

2023-07-11 19:38 UTC, streeve commented on src/runCA.cpp
> +    print.printInitExaCAData<ViewI, ViewF>(id, np, nx, ny, MyYSlices, nzActive, deltax, XMin, YMin, ZMin,
Can it not deduce the template parameters?

2023-07-11 19:38 UTC, streeve commented on unit_test/tstKokkosUpdate.hpp
> +    ViewI GrainID = cellData.getGrainIDSubview();
Can't use `ViewI` becasuse it may not match `TEST_MEMSPACE` (`ViewI_H` is technically okay, but I would still suggest changing to make it a host mirror of the local View typedef). There are probably a couple more instances of this in the tests

2023-07-11 19:40 UTC, MattRolchigo commented on src/runCA.cpp
> +    print.printInitExaCAData<ViewI, ViewF>(id, np, nx, ny, MyYSlices, nzActive, deltax, XMin, YMin, ZMin,
Not sure, I saw the CI failure but when I saw it was something more complicated than I thought I figured I'd deal with it later

2023-07-11 19:59 UTC, MattRolchigo commented on src/runCA.cpp
> +    print.printInitExaCAData<ViewI, ViewF>(id, np, nx, ny, MyYSlices, nzActive, deltax, XMin, YMin, ZMin,
Apparently no, it couldn't deduce the types. The compiler error was: `candidate template ignored: deduced conflicting types for parameter 'ViewTypeInt' ('View<[...], CellData<Kokkos::HostSpace>::memory_space>' vs. 'View<[...], (no argument)>')
    void printFinalExaCAData(int id, int np, int nx, int ny, int nz, int MyYSlices, int NumberOfLayers,`

2023-07-11 20:36 UTC, MattRolchigo commented
@streeve I can't figure out what's going wrong here but it's something with the template types/test types not matching I think

2023-07-13 14:48 UTC, streeve commented on src/CAprint.hpp
> +    void printIntermediateGrainMisorientation(int id, int np, int cycle, int nx, int ny, int nz, int MyYSlices,
This just needs the same change as the function above, I missed this one

2023-07-14 16:17 UTC, streeve approved these changes
@MattRolchigo this is finally passing

2023-07-14 20:06 UTC, merged