New problem type for solidification of a single grain in an initially liquid domain
LLNL/ExaCA pull request #227
Opened 2023-08-22 17:55 UTC by MattRolchigo

The temperature initialization routine was repurposed to allow initialization of both the single grain problem and the directional solidification problem, as both have unidirectional thermal gradients and cooling rates in initially liquid domains. The single grain problem is also unique in the fact that it does not continue until the active layer or the simulation domain has fully solidified, but stops when the grain reaches a simulation edge - this is accounted for in a new `IntermediateOutputAndCheck` routine that is called each time step
Also includes new unit tests for the new substrate init routine, the modified temperature init routine, and the new intermediate output and check routine

Replaces #206 which was out of date

2023-08-23 12:40 UTC, streeve requested changes

2023-08-23 12:40 UTC, streeve commented on unit_test/tstTemperature.hpp
> +    //    testInit_UnidirectionalGradient("SingleGrain", 0);
Why are these commented?

2023-08-23 12:40 UTC, streeve commented on src/CAtemperature.hpp
> +                UndercoolingCurrent(index) = initUndercooling;
Needs to be “local”

2023-08-23 12:40 UTC, streeve commented on unit_test/tstCellData.hpp
> +    ViewF GrainUnitVector(Kokkos::ViewAllocateWithoutInitializing("GrainUnitVector"), 9);
Don’t these need to be local view typedefs?

2023-08-23 13:02 UTC, MattRolchigo commented on unit_test/tstTemperature.hpp
> +    //    testInit_UnidirectionalGradient("SingleGrain", 0);
Probably because I meant to mark this as draft but forgot...

2023-08-24 13:40 UTC, streeve approved these changes

2023-08-24 13:40 UTC, streeve commented on src/CAupdate.cpp
> +    MPI_Allreduce(&XSwitchLocal, &XSwitch, 1, MPI_INT, MPI_MAX, MPI_COMM_WORLD);
Just a note that `XSwitch` is not the most clear variable name

2023-08-24 20:04 UTC, streeve commented on src/CAupdate.cpp
> +    MPI_Allreduce(&XSwitchLocal, &XSwitch, 1, MPI_INT, MPI_MAX, MPI_COMM_WORLD);
I don't know, something about the simulation ending. But definitely within a stand-alone variable rename PR

2023-08-24 20:27 UTC, merged