Struct to hold input parameters
LLNL/ExaCA pull request #239
Opened 2023-10-11 18:25 UTC by MattRolchigo

@streeve Is there a good way to make a copy of a sub-struct inside of `Inputs` (i.e., `Inputs.TemperatureInputs`) and create a modifiable version inside of a different struct (i.e., inside of `Temperature` in CAtemperature.hpp)? That way I don't have to add `inputs` as an input parameter to so many other functions

2023-10-11 21:19 UTC, streeve requested changes

2023-10-11 21:19 UTC, streeve commented on src/CAprint.hpp
> +// Struct to hold data printing options and functions (would ideally just store a copy of Inputs.printInputs here)
You can do that - it can be a member `PrintInputs inputs` and then `: _inputs( inputs )` in the constructor member initialization

2023-10-11 21:19 UTC, streeve commented on src/CAprint.hpp
> +        BaseFileName = inputs.printInputs.BaseFileName;
I think if you pass the `PrintInputs` you may as well store that directly and then just use it directly throughout the class

2023-10-11 21:19 UTC, streeve commented on src/runCA.cpp
> +    // Read input file - toggle appropriate print options
What do you mean about the print options?

2023-10-11 21:19 UTC, streeve commented on src/CAinputs.hpp
> +template <typename MemorySpace>
You're not using the memory space anywhere, should be able to just remove it

2023-10-11 21:19 UTC, streeve commented on src/runCA.cpp
> +    int nx = inputs.domainInputs.nx;
I don't really understand - this has to be read in from the input file, right? Why are we keeping this here instead of passing `DomainInputs` where it's needed (including the eventual grid class)?

2023-10-11 21:36 UTC, MattRolchigo commented on src/CAghostnodes.cpp
> -#include "CAupdate.hpp"
I kept getting annoying linker errors/duplicate functions during compilation, so I changed files so that each cpp file only has a #include for its corresponding header file, which in turns has the other include statements.

2023-10-11 21:38 UTC, MattRolchigo commented on src/CAprint.cpp
>  void PrintExaCATiming(int np, double InitTime, double RunTime, double OutTime, int cycle, double InitMaxTime,
Yeah, the next one after this will be the `Grid` class since it'll be the most significant number of remaining variables that I'll be able to remove from `main`, then the `Octahedra/Halo` and then the timing will be all that's left before we have an entirely struct-oriented code

2023-10-11 21:42 UTC, MattRolchigo commented on src/CAinputs.hpp
> +    Inputs(){};
That's by design for the unit tests, where we want to initialize the struct with some parameters to default values, and others that get set manually. Since a lot of unit tests require the inputs class but few of them require everything in the inputs class, I made this empty constructor

2023-10-11 21:44 UTC, MattRolchigo commented on src/CAcelldata.hpp
> +    void init_substrate(int nx, int ny, int nz, int DomainSize, double *ZMaxLayer, double ZMin, double deltax,
Yeah, that's what I want to do when by initializing copies of the sub-structs like SubstrateInputs in the constructors of the other structs. That way I don't have to pass `inputs.substrateInputs` every time I want to call something in celldata since it already has a copy of the relevant portion of `inputs`

2023-10-11 21:44 UTC, MattRolchigo commented on src/CAinputs.hpp
> +    DomainInputs domainInputs;
The reason I didn't do that is because some of these like `temperature` and `nucleation` are already struct names

2023-10-11 21:46 UTC, MattRolchigo commented on src/CAinputs.hpp
> +    double RNGSeed = 0.0;
Yeah, ideally could have substrate/powder generation and nucleation site/undercooling generation be different seeds. That way you could have the same baseplate every time and see how it evolves for different nucleation seeds and things like that

2023-10-11 21:48 UTC, streeve commented on src/CAghostnodes.cpp
> -#include "CAupdate.hpp"
I saw that, but you didn't add it to the header in this case

2023-10-11 21:49 UTC, MattRolchigo commented on src/runCA.cpp
> +    // Read input file - toggle appropriate print options
Yeah probably an unnecessary confusing comment, the inputs constructor initializes the print inputs just like it initialized all the other inputs. Partially left over from master where we initialize an empty `print` struct first, then fill it during `InputReadFromFile`

2023-10-11 21:50 UTC, MattRolchigo commented on src/CAinputs.hpp
> +template <typename MemorySpace>
I was torn on this especially since I try to avoid templates when I don't need them, but then I realized there's probably going to be inputs that are stored in view form (for example, if we have a kokkos::view of LayerHeight values instead of a scalar value) at some point. Though I'm more than happy to just get rid of the template and cross that bridge when we come to it

2023-10-11 21:56 UTC, streeve commented on src/CAinputs.hpp
> +    Inputs(){};
Which is reasonable, but leaving things that don’t have an obvious default in a more obvious “this never got set” rather than actually uninitialized is probably best

2023-10-11 21:56 UTC, MattRolchigo commented on src/runCA.cpp
> +    int nx = inputs.domainInputs.nx;
This is where the multilayer vs not-multilayer stuff gets confusing. `nx` goes uninitialized for problem type R - it is only known once we call `FindXYZBounds` (part of the future constructor for the `grid` class). Since I want parameters like `nx` to live inside the future grid class, I considered this to be an easier intermediate step since I intend to have the grid struct create its own `nx` by either copying the value from `inputs` or by calculating it, and that I wouldn't touch `inputs.domainInputs.nx` again

2023-10-11 21:57 UTC, streeve commented on src/CAinputs.hpp
> +template <typename MemorySpace>
Agreed on both counts

2023-10-11 21:59 UTC, MattRolchigo commented on src/CAghostnodes.cpp
> -#include "CAupdate.hpp"
We temporarily put `calcCritDiagonalLength` in `CAfunctions.hpp` at some point (will be part of the `Octahedron` class in the future)

2023-10-11 21:59 UTC, streeve commented on src/CAinputs.hpp
> +    DomainInputs domainInputs;
Sure, but this local variable can still be ‘TemperateInputs temperature;’. I don’t think that’s confusing given it’s inside the inputs class

2023-10-12 16:29 UTC, streeve commented on src/CAghostnodes.cpp
> -#include "CAupdate.hpp"
My bad

2023-10-12 18:47 UTC, MattRolchigo commented on src/runCA.cpp
> +    int nx = inputs.domainInputs.nx;
Right, we'd want different `inputs` and `grid` classes for multilayer and non-multilayer problems. I thought of just having a combined inputs+grid class so that the same variables are stored for all problem types, but I figured that could get messy and it probably makes more sense to have separate code paths for the two problem types with their own versions of `inputs` and `grid` in the future

2023-10-12 20:07 UTC, MattRolchigo commented on src/ExaCA.hpp
> -#include "CAfunctions.hpp"
Would it make more sense to remove ExaCA.hpp as a file instead and move everything into runCA.hpp? It keeps with the syntax of having a *.hpp file corresponding to each *.cpp file

2023-10-12 20:38 UTC, streeve commented on src/ExaCA.hpp
> -#include "CAfunctions.hpp"
I mean this was my attempt to trick you into using the one I prefer. I just think it's a more intuitive top-level name (ExaCA.hpp and ExaCA.cpp)

2023-10-16 13:07 UTC, streeve commented on unit_test/tstUpdateMPI.hpp
> +    Inputs inputs;
Could just create `SubstrateInputs` directly. For the comment, I think "default" is more clear than empty

2023-10-16 13:13 UTC, MattRolchigo commented on unit_test/tstInitializeMPI.hpp
> -    testInputReadFromFile(0);
Yeah, it also no longer uses MPI (which wasn't used/necessary but was in there for some reason)

2023-10-18 18:59 UTC, streeve approved these changes

2023-10-19 13:17 UTC, merged