Layerwise grain nuclei init
LLNL/ExaCA pull request #50
Opened 2022-03-11 15:23 UTC by MattRolchigo

Perform the initialization of active cells and nuclei locations/time step values at the beginning of each layer, rather than all during code initialization, to avoid iteration over sites that are not considered in the present layer of multilayer simulations. As GrainInit/NucleiInit are presently performed on the host, the device data is copied back to the host for initialization of the next layer, then copied back (future plans to move both subroutines to the device). Added unit tests for the modified GrainInit and NucleiInit subroutines.

2022-03-16 15:22 UTC, streeve commented
Have you tested performance with this? Maybe I'm wrong, but I would expect this many copies back and forth each step to take quite a bit of time. Regardless, it will be much simpler with random generation on the device preceding this PR

2022-03-16 15:33 UTC, MattRolchigo commented
There will be a performance hit due to the deep copies from, and then back to the device - but since those copies are only done at the end of each layer (as opposed to each time step), performance won't be significantly affected (maybe a couple of seconds slower per layer at most)

2022-03-25 18:57 UTC, streeve requested changes
Just clean up in a few places.

2022-03-25 18:57 UTC, streeve commented on src/CAinitialize.cpp
>                      // If part of the active domain, calculate Critical diagonal lengths
So this is identical to what's in the cell capture routine? This should just be a regular function with the `KOKKOS_INLINE_FUNCTION` macro before it

2022-03-25 19:06 UTC, MattRolchigo commented on src/CAinitialize.cpp
> -    // Remove delay cells not bordering others
It potentially could've been removed in a previous PR, but I tested the code for a number of problems and with the current state of GrainInit, the "Remove delay cells not bordering others" is never entered, so I just removed it alongside the current modifications to GrainInit

2022-03-25 19:13 UTC, streeve commented on unit_test/tstKokkosInit.hpp
> +    EXPECT_FLOAT_EQ(CritDiagonalLength(26), 1.7009771);
Can you add that in the comment? I'll probably ask again otherwise

2022-03-25 19:23 UTC, MattRolchigo commented on src/CAinitialize.cpp
>                      // If part of the active domain, calculate Critical diagonal lengths
It's not identical, but they share a lot of the same functionality. Once the initialization is moved to the device in a later PR, the calculation of critical diagonal lengths for an active cell could be converted to a separate function (since this routine, CellCapture, and GhostNodes1D/2D all use small variations on the same equations)

2022-03-29 17:59 UTC, streeve approved these changes
Full disclosure: this isn't a full review of the tests/nucleation physics. But the Kokkos/c++ side looks good

2022-03-29 18:37 UTC, merged