Output improvements
LLNL/ExaCA pull request #6
Opened 2021-09-04 07:07 UTC by MattRolchigo

While this works as-is, there are repeated functions from src/CAinitialize.cpp inside of analysis/FileReadFunctions.cpp - ideally, the 3 "analysis" cpp files and header would be compiled with some dependency on the main ExaCA-Kokkos executable. The analysis files also do not follow the same clang format as the rest of the code.

2021-09-07 20:00 UTC, streeve requested changes
Just a first pass - need to fix CI errors and warnings as well

2021-09-07 23:02 UTC, streeve commented on analysis/DataAnalysis_main.cpp
> +    if (argc < 2) {
Instead, add all these command line args to the analysis input file

2021-09-09 19:01 UTC, streeve commented on analysis/FileReadFunctions.cpp
> +    AnalysisFile = "analysis/" + BaseFileName + ".txt";
Should pass a path on the command line as well

2021-09-09 22:20 UTC, streeve commented on .github/workflows/CI.yml
> +        working directory: analysis
`working-directory`

2021-09-10 16:36 UTC, streeve requested changes
I got the grain analysis running in the CI, but now it seg faults

2021-09-11 02:07 UTC, MattRolchigo commented on analysis/src/runGA.cpp
> +        PrintExaConstitRVEData(NumberOfRVEs, BaseFileName, nx, ny, nz, deltax, GrainID, XLow_RVE, XHigh_RVE, YLow_RVE,
Yes - I'll make that more clear in the analysis file

2021-09-11 02:07 UTC, MattRolchigo commented on analysis/examples/Inp_Analysis_DirSol.txt
> +Used in post-processing script to analyze select ExaCA outputs
Sure, it makes sense to number them since they're numbered inside of runCA.cpp

2021-09-11 05:26 UTC, MattRolchigo commented on src/CAprint.cpp
> +        int *RecvXOffset = new int[np];
Other than the one bool array "Melted" (which would require changing code in a few other files), I changed the arrays in CAprint.cpp to views.

2021-09-13 14:55 UTC, streeve reviewed
Should be the last round of review - looks pretty much ready to go. Any plans on how long to support the old output options?

2021-09-13 14:55 UTC, streeve commented on analysis/src/runGA.cpp
> +        // and
Just FYI, clang-format will break lines above the limit, but it won't recombine already split comment lines like this one

2021-09-13 14:55 UTC, streeve commented on src/CAprint.cpp
> +                IntVar_WholeDomain(k, i, j) = 0;
This View should just not use `AllocateWithoutInit` instead (probably want a comment saying that it's purposely using the built-in zero init)

2021-09-13 14:55 UTC, streeve commented on src/CAprint.cpp
> +                FloatVar_WholeDomain(k, i, j) = 0.0;
Same here - don't use `AllocateWithoutInit` and remove the loop

2021-09-13 14:55 UTC, streeve commented on src/CAprint.cpp
> +                IntVar_WholeDomain(k, i, j) = 0;
Same here

2021-09-13 14:55 UTC, streeve commented on analysis/src/GAprint.hpp
> +#include <cmath>
Just checking all these are definitely needed includes..

2021-09-13 14:55 UTC, streeve commented on analysis/src/runGA.cpp
> +        throw std::runtime_error("Error: Analysis file name must be given on the command line");
"file path must be given"

2021-09-13 14:55 UTC, streeve commented on examples/Inp_SmallDirSolidification.txt
> +Path to output: ./
May want to update all the input files to be more generic

2021-09-13 14:55 UTC, streeve commented on src/CAprint.hpp
>  #include <vector>
I don't think you need `<vector>` anymore

2021-09-13 21:26 UTC, MattRolchigo commented on analysis/src/GAprint.hpp
> +#include <cmath>
As far as I can tell, they're all used at least once

2021-09-13 23:34 UTC, streeve requested changes
Because we don't have GPU CI yet, have you tested on Cuda and HIP?

2021-09-13 23:34 UTC, streeve commented on src/CAprint.cpp
> +        ViewI3D_H GrainID_WholeDomain("GrainID_WholeDomain", 0, 0, 0);
Okay I actually missed what you were doing here. In this case you want to default construct these and you don't want to zero init because the resize will do that by default. If we didn't want the zero init on resize, `Kokkos::resize( Kokkos::WithoutInitializing, view_name, size_x ... )` is the sytax

2021-09-13 23:34 UTC, streeve commented on README.md
> +If the "Print Paraview vtk file of all ExaCA data for post-processing" options is toggled within an input file, post-processing can be performed on the output data set using the code inside of the `a
```suggestion
If the "Print Paraview vtk file" option is turned on within an input file, post-processing can be performed on the output data set. This functionality is a separate executable from ExaCA, located in the `analysis/` directory and is linked to the ExaCA library for input utilities. 

Running ExaCA for the test problem `Inp_DirSolidification.txt` yields the output files `TestProblemDirS.vtk` and `TestProblemDirS.log`. To analyze this data, run `grain_analysis` (installed in the same location as `ExaCA-Kokkos`), with one command line argument pointing to the analysis input file. Within the `analysis/examples` directory, there are example analysis input files:
```

2021-09-13 23:34 UTC, streeve commented on README.md
> +The path to the associated files `TestProblemDirS.vtk` and `TestProblemDirS.log` is an input within `TestProblemDirS.txt`.
```suggestion
Note that the path to the files needed for analysis, e.g. `TestProblemDirS.vtk` and `TestProblemDirS.log`, are configurable inputs within the analysis input file.
```

2021-09-13 23:34 UTC, streeve commented on src/CAprint.cpp
> +                    IntVar_WholeDomain(k, i - 1, j - 1) = 0;
Should already be zero init - unless I misunderstand the local/global

2021-09-13 23:34 UTC, streeve commented on src/CAprint.cpp
> +                IntVar_WholeDomain(k, i, j) = 0;
Missed one?

2021-09-14 14:29 UTC, streeve commented on src/CAprint.cpp
> +        ViewI3D_H GrainID_WholeDomain(Kokkos::ViewAllocateWithoutInitializing("GrainID_WholeDomain"), 0, 0, 0);
Can't you default construct these?

2021-09-15 14:32 UTC, streeve approved these changes

2021-09-15 17:51 UTC, merged