Optimized nucleation; grain/nuclei seed control
LLNL/ExaCA pull request #60
Opened 2022-04-08 23:28 UTC by MattRolchigo

2022-04-12 19:45 UTC, streeve commented
@MattRolchigo lot's of conflicts here...

2022-04-13 03:50 UTC, MattRolchigo commented
Branch has been updated after resolution of merge conflicts introduced by the earlier changes to master today

2022-04-13 18:24 UTC, streeve reviewed
First round of review

2022-04-13 21:24 UTC, MattRolchigo commented on unit_test/tstKokkosUpdate.hpp
> +    Kokkos::deep_copy(CellType_Host, CellType);
In this case, I thought it was easier to create CellType and GrainID on the host to set initial values of individual view elements for the test, then create device mirrors to be used in "Nucleation", then copy the results back to the host views

2022-04-14 16:34 UTC, streeve commented on unit_test/tstKokkosUpdate.hpp
> +    Kokkos::deep_copy(CellType_Host, CellType);
Makes sense, but you should still mirror copy back here - deep copy always does the copy even if not needed

2022-04-14 16:34 UTC, streeve commented on unit_test/tstKokkosUpdate.hpp
> +    Kokkos::deep_copy(CellType_Host, CellType);
Makes sense, but you should still mirror copy back here - deep copy always does the copy even if not needed

2022-04-20 21:04 UTC, streeve requested changes

2022-04-20 21:04 UTC, streeve commented on unit_test/tstKokkosInit.hpp
> +                        CritDiagonalLength_Expected(0) = 1.7009771;
Make the values to check against a std::vector and loop

2022-04-21 22:20 UTC, MattRolchigo commented on unit_test/tstKokkosInit.hpp
> +                EXPECT_GT(GrainID_Host(i), 0);
It is weaker in one way but stronger in another. The old version of the test checked that each appropriate cell was assigned a specific GrainID, while this one just checks that each appropriate cell was assigned a valid grain ID. But the old version was limited because the number of grains was fixed: odd ranks had one set of GrainIDs and even ranks another (since the location of the grains will depend on where the random number generator puts them, we only know the exact GrainIDs to expect if the calculation has been done once before with the exact same domain sizes and number of grains to check against). This version has the number of grains scale with the number of ranks, and also checks that the appropriate number of grains were spawned.

2022-05-05 20:08 UTC, streeve reviewed
Still unresolved comments to address and the formatting needs to be fixed :)

2022-05-05 20:12 UTC, MattRolchigo commented on unit_test/tstKokkosInit.hpp
> +                        std::vector<float> CritDiagonalLength_Expected{
Theoretically, because there would be multiple grain orientations to check, and they'd have different sets of CritDiagonalLength_Expected values. But since we just initialized and checked 1 orientation, I'll move this out of the loop

2022-05-05 21:21 UTC, streeve commented on unit_test/tstKokkosInit.hpp
> +    Kokkos::deep_copy(DiagonalLength_Host, DiagonalLength);
Should all be mirror copies

2022-05-05 21:25 UTC, streeve commented on unit_test/tstKokkosInit.hpp
>  TEST(TEST_CATEGORY, grain_init_tests) {
Are these really all grain init tests? Nice to have some separate categories

2022-05-05 21:33 UTC, MattRolchigo commented on unit_test/tstKokkosInit.hpp
>  TEST(TEST_CATEGORY, grain_init_tests) {
Maybe they could be subcategorized into the ones that explicitly initialize grain structure, versus those that initialize things related to the grain structure

2022-05-05 21:37 UTC, streeve commented on unit_test/tstKokkosInit.hpp
>  TEST(TEST_CATEGORY, grain_init_tests) {
Yeah, let's do that

2022-05-05 21:49 UTC, streeve approved these changes
Standard disclaimer that this approval is based on design and Kokkos, not the details of the nucleation physics

2022-05-06 02:43 UTC, merged