Temporary host view size calc/initialization moved out of main/runCA.cpp
LLNL/ExaCA pull request #74
Opened 2022-06-02 16:00 UTC by MattRolchigo

Created new functions or modified existing subroutines to allocate host copies of device views only in the scope needed

2022-06-02 16:19 UTC, streeve requested changes

2022-06-02 16:19 UTC, streeve commented on src/CAinitialize.cpp
> +    ViewI_H NeighborX_Host(Kokkos::ViewAllocateWithoutInitializing("NeighborX_Host"), 26);
This will be much simpler as a fixed-size array: `Kokkos::Array<int, 26> NeighborX = {0, -1, 0, ...};`

2022-06-02 16:19 UTC, streeve commented on src/CAinitialize.cpp
> +int calcZBound_Low(bool RemeltingYN, std::string SimulationType, int LayerHeight, int layernumber, float *ZMinLayer,
Shouldn't this be in the next PR?

2022-06-02 16:19 UTC, streeve commented on src/CAinitialize.cpp
> +    // These views are initialized to zeros on the host, filled with data, and then copied to the device for layer
Zero init because the full domain isn't filled below?

2022-06-02 16:19 UTC, streeve commented on src/CAinitialize.cpp
> +    CritTimeStep = Kokkos::create_mirror_view_and_copy(Kokkos::DefaultExecutionSpace(), CritTimeStep_Host);
Let's typedef the `DefaultExecutionSpace` and use that. Should make it easier to run on non-default if we want to

2022-06-02 16:30 UTC, MattRolchigo commented on src/CAinitialize.cpp
> +    // These views are initialized to zeros on the host, filled with data, and then copied to the device for layer
For CritTimeStep and UndercoolingChange, yes, because cells that don't have associated temperature data should have zeros for these. For LayerID, the initial value for all cells is -1, so I can change that view to allocate without initializing

2022-06-02 16:49 UTC, streeve commented on src/runCA.cpp
> +    using memory_space = Kokkos::DefaultExecutionSpace::memory_space;
Add this to CAtypes and you can use it everywhere you currently explicitly use the default in a mirror copy

2022-06-02 16:51 UTC, MattRolchigo commented on src/runCA.cpp
> +    using memory_space = Kokkos::DefaultExecutionSpace::memory_space;
So two lines in CAtypes that look like:

using device_memory_space = Kokkos::DefaultExecutionSpace::memory_space;
using host_memory_space = Kokkos::HostSpace::memory_space;

and then using those throughout in the mirror copy statements?

2022-06-02 16:57 UTC, streeve commented on src/runCA.cpp
> +    using memory_space = Kokkos::DefaultExecutionSpace::memory_space;
I would just use HostSpace directly, but the first one yes

2022-06-03 14:00 UTC, streeve reviewed
Should be ready after this

2022-06-03 14:00 UTC, streeve commented on src/CAghostnodes.hpp
> +#include <Kokkos_Array.hpp>
This is in Core

2022-06-03 14:00 UTC, streeve commented on src/CAinitialize.cpp
> +    ViewI_H NeighborX_Host(Kokkos::ViewAllocateWithoutInitializing("NeighborX_Host"), 26);
This line still needs to be removed

2022-06-03 14:00 UTC, streeve commented on src/CAinitialize.cpp
> +int calcZBound_Low(bool RemeltingYN, std::string SimulationType, int LayerHeight, int layernumber, float *ZMinLayer,
Makes sense. Still kind of borderline for inclusion

2022-06-03 14:00 UTC, streeve commented on src/CAinitialize.cpp
> +            "Error: ZBound_High went uninitialized, problem type may not have been a valid option");
Why is this different than the low bound?

2022-06-03 14:00 UTC, streeve commented on src/CAinitialize.cpp
> +    CritTimeStep = Kokkos::create_mirror_view_and_copy(Kokkos::DefaultExecutionSpace(), CritTimeStep_Host);
Unchanged?

2022-06-04 13:09 UTC, streeve commented on src/CAinitialize.cpp
> +    CritTimeStep = Kokkos::create_mirror_view_and_copy(Kokkos::DefaultExecutionSpace(), CritTimeStep_Host);
These should use `memory_space()`, shouldn't they?

2022-06-04 13:09 UTC, streeve commented on src/CAinitialize.cpp
> +            "Error: ZBound_High went uninitialized, problem type may not have been a valid option");
Ok. Adding "must be S or R" is still helpful

2022-06-06 02:52 UTC, streeve approved these changes

2022-06-06 12:17 UTC, merged