Replaced parseCommaSeparatedArgs function usage
LLNL/ExaCA pull request #84
Opened 2022-07-28 20:59 UTC by MattRolchigo

Replaced usage of the (slow) parseCommaSeparatedArgs function by expanding the functionality of the splitString function (fast).

Fixup of #81

2022-07-28 21:41 UTC, streeve requested changes

2022-07-28 21:41 UTC, streeve commented on src/CAparsefiles.cpp
> -void parseCommaSeparatedArgs(std::string AnalysisFile, std::string ReadLine, std::vector<std::string> &ParsedLine) {
Remove the declaration too?

2022-07-28 21:41 UTC, streeve commented on src/CAparsefiles.cpp
> +void splitString(std::string line, std::vector<std::string> &parsed_line, std::string separator = ",",
Is it slower to return the vector instead of modify? Seems easier. If we keep it this way I don't think you need `expected_num_commas` - just use the size of the vector

2022-07-28 23:06 UTC, streeve commented on src/CAparsefiles.cpp
> +    if (separator == ",") {
I don't think this if block is necessary - an error for not finding enough values to fill the vector is reasonable, but `expected_num_commas` is never even used

2022-07-29 13:57 UTC, MattRolchigo commented on src/CAparsefiles.cpp
> +    if (separator == ",") {
`expected_num_commas` is used though. In most cases, the number of commas expected is the size of the line minus 1 (in this case, expected_num_commas is not used). But in one specific case, the number of commas expected is not equivalent to the size of the line - during the call on CAinitialize.cpp line 499, only the first 3 components of the line are to be read, despite 5 commas being expected on the line. I'll rewrite this a little so it's more clear

2022-07-29 14:24 UTC, streeve commented on src/CAparsefiles.cpp
> +    if (separator == ',') {
Should be for any separator

2022-07-29 14:31 UTC, streeve commented on src/CAparsefiles.cpp
> +void splitString(std::string line, std::vector<std::string> &parsed_line, int expected_num_commas,
expected_num_values

2022-07-29 15:01 UTC, streeve approved these changes
Let's squash and merge

2022-07-29 15:07 UTC, merged